### ISSUE TITLE
Village crashes game

### ISSUE THREAD

**Issue by Jamflof** [TeamLapen/Vampirism#279] opened 2018-03-13 00:41 UTC
## Versions
- Minecraft:1.12.1                    
- Forge:1.12.1-forge1.12.1-14.22.1.2481                       
- Vampirism:  1.12-1.3.7                                           

## Issue Description
Minecraft does not want to load Vampirism villages.

## Reproduce Steps 
Have nothing but forge and vampirism installed. I, myself, have Minecraft 1.10, 1.11, and 1.12 installed, as well as the forge variants.

## Additional Information
Description: Exception in server tick loop
java.lang.IllegalAccessError: tried to access field net.minecraft.village.Village.field_75586_a from class de.teamlapen.vampirism.world.villages.VampirismVillage
at de.teamlapen.vampirism.world.villages.VampirismVillage.tick(VampirismVillage.java:222)
at de.teamlapen.vampirism.world.villages.VampirismVillageHelper.tick (VampirismVillageHelper.java38)

This continues for longer, message me if you need more of the log, because I had to type it out by hand on a separate device
(Please don't make me type more)

**Comment by Jamflof** [comment] 2018-03-13 00:42
Oops, forgot to add that you probably need to load in a village, and I am on a Mac OS X

**Comment by maxanier** [comment] 2018-03-15 09:08
Unfortunately I cannot reproduce this (under Linux).

Do you really have just Forge and Vampirism installed?

Could you update to MC 1.12.2 or is there a reason you are using 1.12.1?

**Comment by Jamflof** [comment] 2018-03-20 08:54
I have no internet at home so I can't really update currently. I download almost all of my mods on a seperate device, so installing 
A newer version of  Minecraft means bringing my bulky computer to my friend's house.

**Comment by maxanier** [comment] 2018-03-28 10:07
Hmm that is unfortunate.
Not sure how this issue can even occur. If Vampirism is not able to access that field, something with the Access Transformers seems to be wrong, but that should mean Forge does not work at all.

Which Java version are you using?

**Comment by Rutes** [comment] 2018-05-01 12:33
I feel like my server crashes are also related to villages, but I am definitely running a lot of mods, including Sponge, so it could be the fault of those.

—- Minecraft Crash Report —-

WARNING: coremods are present:
AstralCore (astralsorcery-1.12.2-1.8.9.jar)
CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
FMLPlugin (elulib-0.1.12.jar)
SpongeCoremod (spongeforge-1.12.2-2655-7.1.0-BETA-3064.jar)
llibrary (llibrary-1.7.9-1.12.2.jar)
CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 5/1/18 2:26 AM
Description: Exception ticking world

java.lang.IndexOutOfBoundsException: index (1) must be less than size (1)
at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1177)
at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1159)
at com.google.common.collect.SingletonImmutableList.get(SingletonImmutableList.java:43)
at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:2268)
at net.minecraft.entity.passive.EntityVillager.func_190672_a(EntityVillager.java:862)
at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_74893_a(StructureVillagePieces.java:1791)
at net.minecraft.world.gen.structure.StructureVillagePieces$Church.func_74875_a(StructureVillagePieces.java:379)
at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:603)
at biomesoplenty.common.world.ChunkGeneratorOverworldBOP.func_185931_b(ChunkGeneratorOverworldBOP.java:509)
at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:268)
at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:988)
at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bbc000(PlayerChunkMapEntry.java:1079)
at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
—————————————————————————————

— Head —
Thread: Server thread
Stacktrace:
at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1177)
at com.google.common.base.Preconditions.checkElementIndex(Preconditions.java:1159)
at com.google.common.collect.SingletonImmutableList.get(SingletonImmutableList.java:43)
at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:2268)
at net.minecraft.entity.passive.EntityVillager.func_190672_a(EntityVillager.java:862)
at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_74893_a(StructureVillagePieces.java:1791)
at net.minecraft.world.gen.structure.StructureVillagePieces$Church.func_74875_a(StructureVillagePieces.java:379)
at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:603)
at biomesoplenty.common.world.ChunkGeneratorOverworldBOP.func_185931_b(ChunkGeneratorOverworldBOP.java:509)
at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:268)
at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:988)
at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bbc000(PlayerChunkMapEntry.java:1079)
at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

— Affected level —
Details:
Level name: Midgard
All players: 2 total; [EntityPlayerMP[‘WOLFghost21’/69021, l=’Midgard’, x=-1785.96, y=67.00, z=3170.70], EntityPlayerMP[‘Firestorme13’/89050, l=’Midgard’, x=-781.18, y=69.00, z=-652.70]]
Chunk stats: ServerChunkCache: 1030 Drop: 0
Level seed: 4413434678807135412
Level generator: ID 10 – BIOMESOP, ver 0. Features enabled: true
Level generator options:
Level spawn location: World: (83,69,255), Chunk: (at 3,4,15 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 88395135 game time, 23531535 day time
Level dimension: 0
Level storage version: 0x04ABD – Anvil
Level weather: Rain time: 60931 (now: false), thunder time: 14440 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

— Sponge PhaseTracker —
Details:
Cause Stack: /***************************************************************************************************************/
/* – Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION} */
/* Context: */
/* – Owner: null */
/* – Notifier: null */
/* – Source: null */
/* – CapturedBlocks: CapturedBlocksSupplier{Captured=0} */
/* – BlockItemDrops: BlockItemDropsSupplier{Captured=0} */
/* – BlockItemEntityDrops: BlockItemEntityDropsSupplier{Captured=0} */
/* – CapturedItems: CapturedItemsSupplier{Captured=0} */
/* – CapturedEntities: CapturedEntitiesSupplier{Captured=0} */
/* – CapturedItemStack: CapturedItemStackSupplier{Captured=0} */
/* – EntityItemDrops: null */
/* – EntityItemEntityDrops: null */
/* – BlockEntitySpawns: CapturedBlockEntitySpawnSupplier{Captured=0} */
/* – CapturedBlockPosition: null */
/* – World: WorldServer{Name=Midgard, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0} */
/* – Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION} */
/* Context: */
/* – Owner: null */
/* – Notifier: null */
/* – Source: null */
/* – CapturedBlocks: CapturedBlocksSupplier{Captured=0} */
/* – BlockItemDrops: BlockItemDropsSupplier{Captured=0} */
/* – BlockItemEntityDrops: BlockItemEntityDropsSupplier{Captured=0} */
/* – CapturedItems: CapturedItemsSupplier{Captured=0} */
/* – CapturedEntities: CapturedEntitiesSupplier{Captured=0} */
/* – CapturedItemStack: CapturedItemStackSupplier{Captured=0} */
/* – EntityItemDrops: null */
/* – EntityItemEntityDrops: null */
/* – BlockEntitySpawns: CapturedBlockEntitySpawnSupplier{Captured=0} */
/* – CapturedBlockPosition: null */
/* – World: WorldServer{Name=Midgard, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0} */
/***************************************************************************************************************/

Stacktrace:
at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjg000(MinecraftServer.java:3985)
at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:887)
at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:552)
at java.lang.Thread.run(Thread.java:748)

— System Details —
Details:
Minecraft Version: 1.12.2
Operating System: Linux (amd64) version 4.13.0-38-generic
Java Version: 1.8.0_162, Oracle Corporation
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 11869327976 bytes (11319 MB) / 21474836480 bytes (20480 MB) up to 21474836480 bytes (20480 MB)
JVM Flags: 13 total; -Xms20G -Xmx20G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=35 -XX:G1MaxNewSizePercent=70 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch
IntCache: cache: 2, tcache: 105, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.3.2655 85 mods loaded, 85 mods active
States: ‘U’ = Unloaded ‘L’ = Loaded ‘C’ = Constructed ‘H’ = Pre-initialized ‘I’ = Initialized ‘J’ = Post-initialized ‘A’ = Available ‘D’ = Disabled ‘E’ = Errored

| State | ID | Version | Source | Signature |
|:——— |:——————— |:————————— |:———————————————- |:—————————————- |
| UCHIJAAAA | minecraft | 1.12.2 | minecraft.jar | None |
| UCHIJAAAA | mcp | 9.42 | minecraft.jar | None |
| UCHIJAAAA | FML | 8.0.99.99 | forge.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | forge | 14.23.3.2655 | forge.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | creativecoredummy | 1.0.0 | minecraft.jar | None |
| UCHIJAAAA | spongeapi | 7.1.0-SNAPSHOT-7d8a938 | spongeforge-1.12.2-2655-7.1.0-BETA-3064.jar | None |
| UCHIJAAAA | sponge | 1.12.2-2655-7.1.0-BETA-3064 | spongeforge-1.12.2-2655-7.1.0-BETA-3064.jar | 6729a677746f8cf63ef31881f913ed15d431b7f0 |
| UCHIJAAAA | elucore | 1.0 | minecraft.jar | None |
| UCHIJAAAA | biomesoplenty | 7.0.1.2387 | BiomesOPlenty-1.12.2-7.0.1.2387-universal.jar | None |
| UCHIJAAAA | craftstudioapi | 1.0.0 | CraftStudio-1.0.0.93-mc1.12-alpha.jar | None |
| UCHIJAAAA | animania | 1.4.7 | animania-1.12.2-1.4.8.jar | None |
| UCHIJAAAA | antiqueatlas | 4.4.7 | antiqueatlas-1.12.2-4.4.7.jar | None |
| UCHIJAAAA | examplemod | 1.0 | antiqueatlas-1.12.2-4.4.7.jar | None |
| UCHIJAAAA | tammodized | 0.15.5 | TamModized-1.12.1-0.15.5.jar | None |
| UCHIJAAAA | aov | 0.8.12 | AoV-1.12-0.8.12.jar | None |
| UCHIJAAAA | architecturecraft | @VERSION@ | architecturecraft-1.12-2.68.jar | None |
| UCHIJAAAA | aroma1997core | 1.3.0.2 | Aroma1997Core-1.12.2-1.3.0.2.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
| UCHIJAAAA | aromabackup | 2.1.1.3 | AromaBackup-1.12.2-2.1.1.3.jar | dfbfe4c473253d8c5652417689848f650b2cbe32 |
| UCHIJAAAA | aromabackuprecovery | 2.1.1.3 | AromaBackup-1.12.2-2.1.1.3.jar | None |
| UCHIJAAAA | baubles | 1.5.2 | Baubles-1.12-1.5.2.jar | None |
| UCHIJAAAA | astralsorcery | 1.8.9 | astralsorcery-1.12.2-1.8.9.jar | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
| UCHIJAAAA | jei | 4.9.1.168 | jei_1.12.2-4.9.1.168.jar | None |
| UCHIJAAAA | base | 3.7.1 | base-1.12.2-3.7.1.jar | None |
| UCHIJAAAA | bibliocraft | 2.4.3 | BiblioCraft[v2.4.3][MC1.12.0].jar | None |
| UCHIJAAAA | chameleon | 1.12-4.1.3 | Chameleon-1.12-4.1.3.jar | None |
| UCHIJAAAA | clayworldgen | 1.1.0-1.12 | ClayWorldGen-1.1.0-1.12.0.jar | None |
| UCHIJAAAA | clumps | 2.0.0 | Clumps-3.0.0.jar | None |
| UCHIJAAAA | cosmeticarmorreworked | 1.12.2-v1 | CosmeticArmorReworked-1.12.2-v1.jar | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
| UCHIJAAAA | craftablehorsearmour | 1.3 | CraftableHorseArmour-1.3.0-1.12.jar | None |
| UCHIJAAAA | creativecore | 1.9.9 | CreativeCore_v1.9.22_mc1.12.2.jar | None |
| UCHIJAAAA | customnpcs | 1.12 | CustomNPCs_1.12.2(20jan18).jar | None |
| UCHIJAAAA | dungeontactics | DT-0.14.2 | DungeonTactics-1.12.2-0.14.2.jar | None |
| UCHIJAAAA | dynamictrees | 1.12.2-0.7.6 | DynamicTrees-1.12.2-0.7.6.jar | None |
| UCHIJAAAA | dynamictreesbop | 1.0.0 | dynamictreesbop-1.0.0.jar | None |
| UCHIJAAAA | dynmap | 3.0-alpha-1-11 | Dynmap-3.0-alpha-1-forge-1.12.2.jar | None |
| UCHIJAAAA | economylite | 2.13.0 | EconomyLite-7.0.0-2.13.0.jar | None |
| UCHIJAAAA | ebwizardry | 4.1.1 | Electroblob’s Wizardry – 4.1.1 – MC 1.12.2.jar | None |
| UCHIJAAAA | embers | 0.230 | embers-0.230.jar | None |
| UCHIJAAAA | fairylights | 2.1.2 | fairylights-2.1.2-1.12.x.jar | None |
| UCHIJAAAA | fastleafdecay | v14 | FastLeafDecay-v14.jar | None |
| UCHIJAAAA | griefprevention | 1.12.2-4.3.0.562 | griefprevention-1.12.2-4.3.0.562.jar | None |
| UCHIJAAAA | guideapi | 1.12-2.1.5-60 | Guide-API-1.12-2.1.5-60.jar | None |
| UCHIJAAAA | waila | 1.8.24 | Hwyla-1.8.24-B39_1.12.jar | None |
| UCHIJAAAA | llibrary | 1.7.9 | llibrary-1.7.9-1.12.2.jar | None |
| UCHIJAAAA | iceandfire | 1.4.0 | iceandfire-1.4.0-1.12.2.jar | None |
| UCHIJAAAA | inventorytweaks | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
| UCHIJAAAA | ironchest | 1.12.2-7.0.40.824 | ironchest-1.12.2-7.0.40.824.jar | None |
| UCHIJAAAA | jaff | 1.7_for_1.12 | JustAFewFish-1.7_for_1.12.jar | None |
| UCHIJAAAA | langswitch | 1.1.1 | LangSwitch.jar | None |
| UCHIJAAAA | latch | 0.4.8 | latch-0.4.8.jar | None |
| UCHIJAAAA | lessforgivingvoid | 1.0.1 | LessForgivingVoid-1.0.1.jar | None |
| UCHIJAAAA | levelup2 | ${version} | Level Up! 2-1.1.19-1.12.jar | None |
| UCHIJAAAA | luckperms | 4.1.7 | LuckPerms-Sponge-4.1.7.jar | None |
| UCHIJAAAA | maille | 2.0 | Maille1.12.2-2.0.jar | None |
| UCHIJAAAA | mantle | 1.12-1.3.2.24 | Mantle-1.12-1.3.2.24.jar | None |
| UCHIJAAAA | mmcrestrict | 1.4.2 | MMCRestrict-1.4.2-API-7.jar | None |
| UCHIJAAAA | morpheus | 1.12-3.3.2 | Morpheus-1.12-3.3.2.jar | None |
| UCHIJAAAA | nex | 2.1.14.15 | NetherEx-1.12-2.1.14.15.jar | None |
| UCHIJAAAA | nucleus | 1.3.7-S7.0 | Nucleus-1.3.7-S7.0-MC1.12.2-plugin.jar | None |
| UCHIJAAAA | playerrevive | 1.0 | PlayerRevive_v1.2.13_mc1.12.2.jar | None |
| UCHIJAAAA | pjc | 0.2.1 | projectcore-7.0.0-0.2.1.jar | None |
| UCHIJAAAA | pjp | 0.14.3 | projectportals-7.1.0-0.14.3.jar | None |
| UCHIJAAAA | roguelike | 1.8.0 | RoguelikeDungeons-1.12.2-1.8.0.jar | None |
| UCHIJAAAA | roots | 0.104 | roots-2-0.104.jar | None |
| UCHIJAAAA | rustic | 1.0.3 | rustic-1.0.3.jar | None |
| UCHIJAAAA | serverlistplus | 3.4.7 | ServerListPlus-3.4.7-Universal.jar | None |
| UCHIJAAAA | simpleautorun | 1.12.1-1.2 | simpleautorun-1.12.2-1.2.0.jar | None |
| UCHIJAAAA | skylands | 1.5.5 | skylands-1.5.5.jar | None |
| UCHIJAAAA | spartanshields | 1.4.1 | SpartanShields-1.12.2-1.4.1.jar | None |
| UCHIJAAAA | stg | 1.12.2-1.2.3 | stg-1.12.2-1.2.3.jar | None |
| UCHIJAAAA | storagedrawers | 1.12-5.3.5 | StorageDrawers-1.12.2-5.3.6.jar | None |
| UCHIJAAAA | tconstruct | 1.12.2-2.9.1.65 | TConstruct-1.12.2-2.9.1.65.jar | None |
| UCHIJAAAA | tombstone | 2.9.0 | tombstone-2.9.0-1.12.jar | None |
| UCHIJAAAA | toroquest | 1.12.2-5.2 | toroquest-1.12.2-5.2.jar | None |
| UCHIJAAAA | totemic | 1.12.2-0.10.3 | Totemic-1.12.2-0.10.3.jar | 21d11d7bf4d97b465382a1f95428029aac6daaea |
| UCHIJAAAA | jdalibraryloader | 1.0.0 | UltimateChat-JDA.jar | None |
| UCHIJAAAA | ultimatechat | 1.8.5 | UltimateChat-1.8.5-b151-Universal.jar | None |
| UCHIJAAAA | vampirism | 1.4.0 | Vampirism-1.12.2-1.4.0.jar | None |
| UCHIJAAAA | teamlapen-lib | 1.4.0 | Vampirism-1.12.2-1.4.0.jar | None |
| UCHIJAAAA | vshop | 1.8.1 | VillagerShops.jar | None |
| UCHIJAAAA | wawla | 2.5.253 | Wawla-1.12.2-2.5.253.jar | d476d1b22b218a10d845928d1665d45fce301b27 |
| UCHIJAAAA | waystones | 4.0.42 | Waystones_1.12.2-4.0.42.jar | None |
| UCHIJAAAA | wearablebackpacks | 3.1.2 | WearableBackpacks-1.12.2-3.1.2.jar | None |
| UCHIJAAAA | worldedit | 6.1.8 | worldedit-forge-mc1.12-6.1.8-dist.jar | None |
| UCHIJAAAA | elulib | 0.1.12 | elulib-0.1.12.jar | None |

Loaded coremods (and transformers):
AstralCore (astralsorcery-1.12.2-1.8.9.jar)

CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)

Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
invtweaks.forge.asm.ContainerTransformer
FMLPlugin (elulib-0.1.12.jar)
elucent.elulib.asm.ASMTransformer
SpongeCoremod (spongeforge-1.12.2-2655-7.1.0-BETA-3064.jar)
org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
llibrary (llibrary-1.7.9-1.12.2.jar)
net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)

Pulsar/tconstruct loaded Pulses:
– TinkerCommons (Enabled/Forced)
– TinkerWorld (Enabled/Not Forced)
– TinkerTools (Enabled/Not Forced)
– TinkerHarvestTools (Enabled/Forced)
– TinkerMeleeWeapons (Enabled/Forced)
– TinkerRangedWeapons (Enabled/Forced)
– TinkerModifiers (Enabled/Forced)
– TinkerSmeltery (Enabled/Not Forced)
– TinkerGadgets (Enabled/Not Forced)
– TinkerOredict (Enabled/Forced)
– TinkerIntegration (Enabled/Forced)
– TinkerFluids (Enabled/Forced)
– TinkerMaterials (Enabled/Forced)
– TinkerModelRegister (Enabled/Forced)
– wailaIntegration (Enabled/Not Forced)

Profiler Position: N/A (disabled)
Player Count: 2 / 9001; [EntityPlayerMP[‘WOLFghost21’/69021, l=’Midgard’, x=-1785.96, y=67.00, z=3170.70], EntityPlayerMP[‘Firestorme13’/89050, l=’Midgard’, x=-781.18, y=69.00, z=-652.70]]
Is Modded: Definitely; Server brand changed to ‘fml,forge,sponge’
Type: Dedicated Server (map_server.txt)

**Comment by maxanier** [comment] 2018-05-01 13:59
That crash seems to be related to villagers and their trades/professions. This is most likely not related to Vampirism

**Comment by Rutes** [comment] 2018-05-01 14:25
Ah, hmm. I guess I saw $Church and a lot of lines about world gen so figured it might be related to the Altar of Cleansing trying to appear in villages. I posted to the Sponge git as well, maybe they can point me in the right direction.

**Comment by Jamflof** [comment] 2018-05-14 20:17
I am unsure what java i was using, as i had never gotten notifications saying i needed a newer version

**Comment by Jamflof** [comment] 2018-05-14 20:19
i had been running that mod only, so it could possibly have been my forge not working. i will try to install other mods, and see what happens

**Comment by flamechair** [comment] 2018-06-03 04:16
Also experiencing this issue, relevant spongeforge issue: https://github.com/SpongePowered/SpongeForge/issues/2127

With Vampirism disabled, this issue does not occur. Could it be the way you register NPC professions for the Vampire Hunter Trainer? In the SpongeForge issue they mention where the exception happens, so this might be an easy fix for you.

**Comment by maxanier** [comment] 2018-06-09 14:13
Thanks for finding this. 
Vampirism registers a profession (though not for the hunter trainer), so I guess that could trigger the exception.

Maybe I can find a different to register it to avoid this

**Comment by flamechair** [comment] 2018-06-09 17:40
I'll test on the latest versions of sponge tonight to see if they fixed it on their endOn Jun 9, 2018 9:13 AM, Max Becker <notifications@github.com> wrote:Thanks for finding this.
Vampirism registers a profession (though not for the hunter trainer), so I guess that could trigger the exception.
Maybe I can find a different to register it to avoid this

**Comment by Rutes** [comment] 2018-06-10 02:31
The way I'm getting around the crashes currently is by pre-generating my worlds using Nucleus (sponge plugin). If the world is generated by a player, then the crash occurs. I'll test sometime next week with the latest Sponge, but I'm not sure if they've addressed this specifically.

**Comment by flamechair** [comment] 2018-06-10 02:58
I tried generating with the pregen forge plugin, but the crashed still occurs when I visit a village for the first time. I'll have to try it with nucleus, and set a world border to keep any new ones from spawning. What version of sponge  are you using? On Jun 9, 2018 9:31 PM, Rutes <notifications@github.com> wrote:The way I'm getting around the crashes currently is by pre-generating my worlds using Nucleus (sponge plugin). If the world is generated by a player, then the crash occurs. I'll test sometime next week with the latest Sponge, but I'm not sure if they've addressed this specifically.

**Comment by Rutes** [comment] 2018-06-10 03:15
my server is currently running spongeforge-1.12.2-2690-7.1.0-BETA-3115

**Comment by flamechair** [comment] 2018-06-10 22:39
Can confirm this still occurs with the latest version of SpongeForge. I'll test out the workaround using nucleus

**Comment by flamechair** [comment] 2018-06-15 23:18
The crashes that @Rutes and I have been experiencing have been fixed with the latest SpongeForge build.

**Comment by Rutes** [comment] 2018-06-16 00:57
confirmed, no more crashes!

**Comment by Rutes** [comment] 2018-06-16 00:58
@Jamflof is it fixed for you?

**Comment by gabizou** [comment] 2018-06-16 01:15
Give SpongeForge 3188 a shot. I didn't know this issue was open a while back. I went and gutted some of the handling for Sponge to allow plugins to interact with mod provided Villager careers and whatnot. Disabled that for now while a more stable and ensured way will work in the future.

**Comment by maxanier** [comment] 2018-06-20 10:50
Alright, closing this now.
Thanks for looking into it!

*Edit*: I just noticed the original issue here was a different one. So, @Jamflof if your issue should persist (with recent Forge version and preferably reinstalled Java 8) please let me now

**Closed as completed by maxanier** 2018-06-20 10:50 UTC
Labels: bug
