### ISSUE TITLE
[Bug] Crash upon giving up

### ISSUE THREAD

**Issue by YnwLNE** [TeamLapen/Vampirism#985] opened 2021-09-26 05:30 UTC
- Minecraft: 1.16.5
- Forge: 36.2.4
- Vampirism:  Vampirism-1.16.5-1.8.1

- ModPack: N/A

## Issue Description 
Upon dying and giving up, it immediately crashes the game and the player is no longer allowed on the server/world due to being in that state when loading in. I don't know if it's a mod combability as all death related mods when removed didn't fix it but I can give the list as well if needed.

## Reproduce Steps
Die upon first becoming a vampire and try to give up

## Additional Information

crash: The game crashed whilst unexpected error
Error: java.lang.IllegalStateException: Cannot get Vampire player capability from player ClientPlayerEntity['YnwL'/73463, l='ClientLevel', x=776.16, y=71.00, z=97.11]
Exit Code: -1

Here's the log
https://pastebin.com/1PApdL5f

**Comment by Cheaterpaul** [comment] 2021-09-26 10:48
This is caused by classic bar.
Temporarily you can remove classic bar, respawn and add classic bar again.

**Comment by Cheaterpaul** [comment] 2021-09-26 12:06
There is already a fix pending Tfarcenim/ClassicBar#84 but it is not fixed yet

**Comment by Cheaterpaul** [comment] 2022-11-02 15:19
is fixed in classic bar 4.1.1

**Closed as completed by Cheaterpaul** 2022-11-02 15:19 UTC
Labels: bug, external
