### ISSUE TITLE
Ticking entity crash

### ISSUE THREAD

**Issue by Xilef11** [TeamLapen/Vampirism#71] opened 2016-05-16 23:57 UTC
This crash started happening when updating to Vampirism-1.9-1.0.0-Alpha+05-15-12-31
If the Forge option to remove erroring entities is activated, the crash stops, but there are massive lag spikes and it crashes again when the option is disactivated, which indicates that it also affects newly spawned entities.
[Log](https://gist.github.com/Xilef11/469588709f3f35e328253dfd7ffe3eac)

**Comment by maxanier** [comment] 2016-05-21 00:13
Thanks for the report, I will take a look at this as soon as I find time.

**Comment by maxanier** [comment] 2016-05-28 09:03
Finally found the time to investigate this, looks I made quite a stupid mistake.
The issue is fixed now and the updated version should be available on curseforge

**Closed by maxanier** 2016-05-28 09:03 UTC
