### ISSUE TITLE
Cannot place Lava in Hunter Weapon Table

### ISSUE THREAD

**Issue by thtaylor1234** [TeamLapen/Vampirism#189] opened 2017-06-10 03:16 UTC
## Versions
- Minecraft:                    1.10.2
- Forge:                       12.18.3.2316
- Vampirism:       1.1.3                                     

## Issue Description
When I right click with lava bucket on Hunter Weapon table it just opens the table

**Comment by maxanier** [comment] 2017-06-10 09:51
Cannot reproduce :/

Any mods installed?
Is it a vanilla lava bucket?

**Comment by thtaylor1234** [comment] 2017-06-10 18:58
it is a vanilla bucket 

mods installed
ummmm a lot 

are there any known mod conflicts?

**Comment by maxanier** [comment] 2017-06-12 08:19
Do you have any other (modded) container that contains lava? Try that one.

(There are no conflicts I know of, yet)

**Comment by maxanier** [comment] 2017-06-12 08:22
You could try using the Alpha 1.2. There have been some changes made to Fluid stuff, maybe this solves your problem

**Comment by maxanier** [comment] 2017-07-05 18:10
Did that help?

**Comment by maxanier** [comment] 2017-07-13 12:51
Closing because older than 1 month

**Closed as completed by maxanier** 2017-07-13 12:51 UTC
Labels: bug
