### ISSUE TITLE
[Bug]: Items not stacking

### ISSUE THREAD

**Issue by postal291** [TeamLapen/Vampirism#1142] opened 2022-10-22 19:20 UTC
### Minecraft Version

1.19.x

### Forge Version

43.1.47

### Vampirism Version

1.9.0-alpha+20221003-1811

### Singleplayer/Multiplayer

Singleplayer

### What happened?

crafted items aren't stacking with dropped / looted items.

### Reproduce steps

1. Load single player world
2. Acquire wood & craft sticks
3. Break leaves until sticks drop
4. Sticks won't stack.

Bug ceases when vampirism is disabled.

**Comment by Cheaterpaul** [comment] 2022-10-22 21:08
Duplicate of #1139

**Comment by Cheaterpaul** [comment] 2022-10-22 21:09
should be fix with the latest version

**Closed as completed by Cheaterpaul** 2022-10-22 21:08 UTC
Labels: bug, unconfirmed
