### ISSUE TITLE
Blood has to bestackable. Please[Feature]

### ISSUE THREAD

**Issue by blace2121** [TeamLapen/Vampirism#668] opened 2020-04-17 02:51 UTC
## What would you like to have changed or added to Vampirism
You should make blood stackable, and vampires at least need more skill points or it isn't worth playing them.

## Does this make the mod experience more balanced?
Yeah, it sucks to be a vampire. Don't make the same mistake as bethesda please! and mojang already tried to die on the non-stackable food hill.

## Can you provide additional resources (etc. textures or models)
it seems like it at least should be a config option. Without stack-able blood I at least would never play as a vampire, and the same seems to go for everyone on my server. Forcing players to play at night is cool and necessary, but it has to balanced with a lot of power or people will never do it, certainly not by punishing them by making food an unmanageable nightmare.

**Comment by Cheaterpaul** [comment] 2020-04-24 15:39
Duplicate of #581

**Closed as completed** 2020-04-24 15:40 UTC
Labels: duplicate, enhancement, feature, discussion
