### ISSUE TITLE
[Bug]: Concurrent Modification in DistanceManager HashMap

### ISSUE THREAD

**Issue by warden23ou** [TeamLapen/Vampirism#1399] opened 2024-08-05 11:05 UTC
### Minecraft Version

1.20.1

### (Neo)Forge Version

47.3.5

### Vampirism Version

1.10.9

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Hi!my minecraft got crashed without any reasons(game froze,then black screen and game just closed itself) and ppl on forge support said that it's might be because of vampirism,i would like to get a help :(
https://imgur.com/a/mf4eyhm - all mods that were used
i uploaded wrong log last time and noticed it too late 

### Relevant log output

[latest.log](https://github.com/user-attachments/files/16494775/latest.log)
[crash-2024-08-05_13.54.38-server.txt](https://github.com/user-attachments/files/16494778/crash-2024-08-05_13.54.38-server.txt)

**Comment by Leiriad** [comment] 2024-08-13 08:11
I have the same issue on 1.20.1. It appeared when I found the blood feeder's home. I'm a vampire if that matters. Soon after walking in the forest, the game crashes. When I reconnect, I can explore for a few seconds to a few minutes before another crash. My log has the same concurrent modification error. I play on a modpack based on the first Neoforge (forge 47.1.106) on Minecraft 1.20.1. My Vampirism version is 1.10.9.

**Comment by Cheaterpaul** [comment] 2024-08-21 19:36
From the log file I can not tell what the problem is. The errors are just errors in other mods implementation, but shouldn't cause this crash.

The issue's description does suggests that there is something at fault in Vampirism. But it will be hard to find.

**Comment by maxanier** [comment] 2024-08-24 08:17
As Leiriad already figure out (Thank you :raised_hands: !), this appears to be an issue with other mods as well. (based on above crash-report)
https://github.com/AllTheMods/ATM-9/issues/406 

It is not entirely clear what is causing this and if Vampirism is at fault here.

In the ATM issue somebody posted an workaround mod, to replace that list with one that is able to handle concurrent modifications.
https://github.com/AllTheMods/ATM-9/issues/406#issuecomment-1894603547
Unless you have some idea what Vampirism might have to do with this (@Cheaterpaul ), we could also consider adding this workaround and replacing the map (if it wasn't already).

**Comment by maxanier** [comment] 2024-08-24 08:20
I am not sure what the title of this issue has to do with the content...
Please let me know if there is something I am missing

**Comment by Cheaterpaul** [comment] 2024-10-01 10:13
fixed in the latest version

**Closed as completed by Cheaterpaul** 2024-10-01 10:13 UTC
Labels: bug, 1.20
