### ISSUE TITLE
[Bug] Blood Vision causes screen to freeze.

### ISSUE THREAD

**Issue by thedeerirty** [TeamLapen/Vampirism#561] opened 2019-11-28 16:30 UTC
## Versions
- Minecraft:  1.12.2                  
- Forge:  1.12.2                     
- Vampirism: 1.5.5

**Comment by lunofe** [comment] 2019-12-02 07:30
It's very likely that this issue is caused by the shader. However, please provide a proper forge version (visible in the Minecraft launcher and in-game) as well as the exact name and version for the shader, so I can confirm and close this issue.

**Comment by lunofe** [comment] 2019-12-05 10:27
Closing this now because there hasn't been an answer in the last 7 days and as I already said, it's very likely that this was caused by the shader.

**Closed as completed by lunofe** 2019-12-05 10:27 UTC
Labels: NeedsInfo

**Comment by maxanier** [comment] 2019-12-08 14:09
Btw, if you add the NeedsInfo label, it will automatically be closed if there is no response within 3 weeks.
