### ISSUE TITLE
[Bug]: Can't use abilities on server

### ISSUE THREAD

**Issue by LeagueBox** [TeamLapen/Vampirism#1176] opened 2023-01-28 18:24 UTC
### Minecraft Version

1.16.x

### Forge Version

36.2.39

### Vampirism Version

1.9.1

### Singleplayer/Multiplayer

Server

### What happened?

Whenever I try to use vampire abilities, a message is shown: [Vampirism] It seems like the permissions plugin used is not properly set up. Make sure all players have 'vampirism.*' for the mod to work (or at least 'vampirism.check' to suppress this warning).

**Comment by Cheaterpaul** [comment] 2023-01-28 19:25
Duplicate of #1175

**Comment by Cheaterpaul** [comment] 2023-01-28 19:26
Have you tried this?
> Make sure all players have 'vampirism.*' for the mod to work (or at least 'vampirism.check' to suppress this warning).

**Closed as completed by Cheaterpaul** 2023-01-28 19:25 UTC
Labels: bug, unconfirmed

**Comment by LeagueBox** [comment] 2023-01-29 14:32
I used vampirism.* But it shows unknown command. What should I do?

**Comment by Cheaterpaul** [comment] 2023-01-29 14:40
That is no command, it is a permission.
>It seems like the permissions plugin used is not properly set up

You need to setup the permission plugin to allow all players to use the vampirism features
>Make sure all players have 'vampirism.*' for the mod to work (or at least 'vampirism.check' to suppress this warning).

How you do that depends on your permission plugin

[Permissions](https://wiki.vampirism.dev/docs/wiki/permissions)

**Comment by LeagueBox** [comment] 2023-01-29 16:35
What is the name of the plugin?

**Comment by LeagueBox** [comment] 2023-01-29 17:49
How to ise the vampirism.* I can't understand

**Comment by LeagueBox** [comment] 2023-01-30 04:51
> That is no command, it is a permission.
> 
> > It seems like the permissions plugin used is not properly set up
> 
> You need to setup the permission plugin to allow all players to use the vampirism features
> 
> > Make sure all players have 'vampirism.*' for the mod to work (or at least 'vampirism.check' to suppress this warning).
> 
> How you do that depends on your permission plugin
> 
> [Permissions](https://wiki.vampirism.dev/docs/wiki/permissions)

Help me. I like this mod and I want to use it on my server.

**Comment by Cheaterpaul** [comment] 2023-01-30 22:23
You are either using a permission plugin on your server or you are using a hybrid server with bugs.
In the first case you should configure the permission plugin to add the permission `vampirism.*` to every user. In the second case you first need to install a permission plugin (such as Luck Perm) and setup the correct permissions

If you do not know how to add permission to player you should read the documentation of the permission plugin you are using.
