### ISSUE TITLE
Bat not flying 

### ISSUE THREAD

**Issue by Anthony0942** [TeamLapen/Vampirism#952] opened 2021-06-11 20:34 UTC
## Versions

- Minecraft: 1.16.5
- Forge: 36.1.27
- Vampirism: 1.7.12
- ModPack: [ModPack-4000.HELP.zip](https://github.com/TeamLapen/Vampirism/files/6640858/ModPack-4000.HELP.zip)

## Issue Description
I hit level 4 and unlocked the bat however I can't fly and but i can turn into the bat still

## Reproduce Steps
Just go to level 4 and try and fly

**Comment by lunofe** [comment] 2021-06-11 21:58
@maxanier This seems to be a compatability issue with "Create: Stuff Additions" (v1.0.3 used in the pack), an add-on for the Create mod. When only Create is loaded, it works as it should.

**Comment by Anthony0942** [comment] 2021-06-11 23:09
So If i remove Create Stuff Additions it will work?

**Comment by oiirn29** [comment] 2021-06-12 04:44
> @maxanier This seems to be a compatibility issue with "Create: Stuff Additions" (v1.0.3 used in the pack), an add-on for the Create mod. When only Create is loaded, it works as it should.

i have also found that the levitation belt from the ars nouveau mod seems to have problems with bat mode too

**Comment by maxanier** [comment] 2021-06-12 09:15
> > @maxanier This seems to be a compatibility issue with "Create: Stuff Additions" (v1.0.3 used in the pack), an add-on for the Create mod. When only Create is loaded, it works as it should.
> 
> i have also found that the levitation belt from the ars nouveau mod seems to have problems with bat mode too

I assume in this case you always get a levitation or slow falling effect when descending in bat mode?

**Comment by maxanier** [comment] 2021-06-12 09:18
Original issue is duplicate of #911 
Create: Stuff Additions is not open source and I can't even find an issue tracker for it.
So there is nothing I can do, except recommend you to either try to somehow contact its author or get rid of the mod

**Closed as completed by maxanier** 2021-06-12 09:18 UTC
Labels: bug, modcompat

**Comment by oiirn29** [comment] 2021-06-14 15:00
> > > @maxanier This seems to be a compatibility issue with "Create: Stuff Additions" (v1.0.3 used in the pack), an add-on for the Create mod. When only Create is loaded, it works as it should.
> > 
> > 
> > i have also found that the levitation belt from the ars nouveau mod seems to have problems with bat mode too
> 
> I assume in this case you always get a levitation or slow falling effect when descending in bat mode?

yeah that's what happens
