### ISSUE TITLE
[Bug][1.14.4] Server hard lock - Entities- 

### ISSUE THREAD

**Issue by ProsperCraft** [TeamLapen/Vampirism#538] opened 2019-10-10 02:52 UTC
## Versions
- Minecraft:     1.14.4         
- Forge:            forge-1.14.4-28.1.40           
- Vampirism:     Vampirism-1.14.4-1.6.0-alpha+20191006-1207                                          

## Issue Description
Server hard lock when players exploring the server, I kept removing mods that showed up in the stacktrace, and was left with this staktrace(acquired with warmroast) that shows Vampirism.
The hard locks started with the addition of vampirism.

## Additional Information
![2a03421adbdad4c010084371f67b886c](https://user-images.githubusercontent.com/4427684/66535313-692d7b00-ead6-11e9-86d0-2211f4bffb3a.png)

**Comment by ProsperCraft** [comment] 2019-10-10 03:04
Here is another one.

![9c869bae5104d680e74bef8d5766f534](https://user-images.githubusercontent.com/4427684/66535870-59af3180-ead8-11e9-8b9b-f533551a3639.png)

**Comment by ProsperCraft** [comment] 2019-10-10 03:10
[lock.zip](https://github.com/TeamLapen/Vampirism/files/3710283/lock.zip)

Here are the server logs.

**Comment by maxanier** [comment] 2019-10-10 09:11
Unfortunately, the warm roast does not really help much.
Some mod (might be Vampirism, might not be) messes up during world gen and locks a chunk.
Then, as soon as a entity is updated in/near it, it causes the dead lock.
The Vampirism creature is just caught in the "crossfire", it just does vanilla stuff.

I went though Vampirism and looked for occasions where it access a chunk (direct or indirect via an Entity), but couldn't not find anything. Furthermore, Vampirism 1.14 has currently hardly any world gen (forest is mostly vanilla) and I cannot reproduce it with just Vampirism (which should theoretically be possible if it causes this issue), I doubt this is caused by Vampirism.

**Comment by maxanier** [comment] 2019-10-10 09:13
Pls, mention this explanation by gabizou if you open any more issues:
https://github.com/TeamLapen/Vampirism/issues/535#issuecomment-540203350

**Comment by maxanier** [comment] 2019-10-10 09:29
Maybe you can try just removing Vampirism from the original modpack, play a couple of hours and then report if the issue still exist. Just to make sure it is actually caused by Vampirism.

**Comment by ProsperCraft** [comment] 2019-10-10 15:09
Here is the next one, player said he was traveling through a vampire forest.

Removing Vampirism and seeing if we can reproduce.

![455431239d8479345abd78efa371dee3](https://user-images.githubusercontent.com/4427684/66581570-8ea19f80-eb3d-11e9-8099-2c04b0dfee27.png)

**Comment by ProsperCraft** [comment] 2019-10-10 16:47
Removing Vampirism completely resolved the lock ups.

One on my players had two lockup spots bookmarked and went there more then once locking the server with vampirism, then went there once removed and it no longer locks.   Both spots were in vampire forests.  Another player said he was in a vampire forest when he locked the server.

**Comment by maxanier** [comment] 2019-10-10 22:12
Closing this as it is effectively a duplicate of #535

**Closed as completed by maxanier** 2019-10-10 22:12 UTC
Labels: bug, unconfirmed, 1.14

**Comment by ProsperCraft** [comment] 2019-10-11 02:54
The fix seems to have completely fixed the lockups.

**Comment by maxanier** [comment] 2019-10-11 08:20
Perfect :+1: 
Thank you for putting in the work and narrowing it down to Vampirism

**Comment by ProsperCraft** [comment] 2019-10-13 00:24
Looks like we hard locked again, I didn't catch it in time to profile it, here is the watchdog crash

https://gist.github.com/ProsperCraft/73b3fc59f3f97bb9d3c68a5c8dd4421e

Vampirism-1.14.4-1.6.0-alpha+20191011-0002
forge-1.14.4-28.1.40
