### ISSUE TITLE
[Modcompat]: Doctor Who - Reborn incompatibility  

### ISSUE THREAD

**Issue by ImShEthan** [TeamLapen/Vampirism#1341] opened 2024-02-23 17:24 UTC
### Minecraft Version

1.20.x

### Forge Version

47.2.20

### Vampirism Version

1.10.6

### Incompatible mod

dwm v 1.0.7(Doctor Who - Reborn)

### Singleplayer/Multiplayer

Both

### What happened?

When entering the TARDIS from the mod this error pop out : "[18:15:31] [Server thread/WARN] [de.te.va.en.fa.FactionPlayerHandler/]: Cannot get Faction player capability. This might break mod functionality."

**Comment by Cheaterpaul** [comment] 2024-02-23 18:17
Duplicate of #1342

**Closed as not planned by Cheaterpaul** 2024-02-23 18:17 UTC
Labels: bug, modcompat, unconfirmed
