### ISSUE TITLE
Can not place injection chair.

### ISSUE THREAD

**Issue by ecoay** [TeamLapen/Vampirism#160] opened 2017-04-19 01:31 UTC
Minecraft: 1.10.2                    
Forge:  12.18.3.2254                      
 Vampirism: 1.10.2.1  1.1.01 BETA1

*saw you edited template figured id include the information

Is there any way currently to become a vampire hunter in skyblock as the injection chair cannot be placed?

**Comment by ecoay** [comment] 2017-04-19 02:01
Can place chair on wool only. 

can this be fixed? Or maybe a config option not to need to need use of chair as I can grow my own garlic XD

**Comment by maxanier** [comment] 2017-04-23 11:08
Unfortunetely I cannot reproduce this issue, but I have heared about a few similar issues lately, so I will create a special version which prints a few debug information that might help

**Comment by maxanier** [comment] 2017-04-23 11:25
Never mind I found a stupid mistake I made which is probably causing this issue.
Try to place the chair on something two blocks thick. Will be fixed in the next version.

**Closed** 2017-04-23 13:38 UTC
Labels: bug

**Comment by ecoay** [comment] 2017-04-23 14:53
TY You are awesome

https://minecraft.curseforge.com/projects/sky-harvest/issues/2
