### ISSUE TITLE
Optifine with shaders breaks world

### ISSUE THREAD

**Issue by DerHofnarr** [TeamLapen/Vampirism#780] opened 2020-10-02 09:36 UTC
## Versions
- Minecraft: Java 1.16.3                   
- Forge: latest..... just kidding ;) 34.1.1
- Vampirism: Vampirism-1.16.3-1.6.0-alpha+20200927-1208                                       

- ModPack: N/A

## Issue Description

Hi! First of all i love your mod! It has much of potential and its just awsome. Now my issue: since today (02. oct. 2020) everytime i trie to load up the world a message appear "unable to load world... missing data package... try to load vanilla..." when i hit "Load vanilla" nothing happens only thing i can do is go back to the menu. So i cant load the world (in my log i can see "

[02Okt.2020 11:19:53.035] [Render thread/ERROR] [net.minecraft.world.storage.SaveFormat/]: Exception reading /home/derhofnarr/.minecraft/saves/Neie Wöd/level.dat_old
java.lang.IllegalStateException: Missing: ResourceKey[minecraft:worldgen/biome / vampirism:vampire_forest]

"
No crash.log or something just the normal latest.log with 9213 lines (thats why im not attaching it. if you want it just let me know) yesterday everything worked perfectly fine. what i did today is i updated my Nvidia GPU drivers and suddendly got the issue lol :D. I confirmed its the Vampirism mod (by delete and adding it).

OS: Ubuntu 20.04.1 LTS
Gnome : 3.36.3 
Core: IntelCore i7
GPU 1: Intel Corporation HD Graphics 630
GPU 2: NVIDIA Corporation GP107M [GeForce GTX 1050 Mobile]

if you need anything let me know. cheers :-)
P.s. sorry for my bad english its not my native language.

## Additional Information

No crash.log only latest.log with the line :" 

[02Okt.2020 11:19:53.035] [Render thread/ERROR] [net.minecraft.world.storage.SaveFormat/]: Exception reading /home/derhofnarr/.minecraft/saves/Neie Wöd/level.dat_old
java.lang.IllegalStateException: Missing: ResourceKey[minecraft:worldgen/biome / vampirism:vampire_forest]

" (that was when i tried load up the world)

**Comment by maxanier** [comment] 2020-10-02 10:07
This is really strange, so you did not update anything (except GPU drivers) and did not change any configuration?
Can you upload the full debug.log: e.g. here: https://paste.gg/
Thank you

**Comment by DerHofnarr** [comment] 2020-10-02 10:18
@maxanier thats correct. all i did was "Playing arround" with my GPU drivers to get my GPU back to work. But NOT Minecraft, The world or even the Mod (dont even know how :D) log will be uploaded. (Link: https://paste.gg/p/anonymous/d667870825da4722b2071ef7806c4b04 )

**Comment by maxanier** [comment] 2020-10-02 10:34
thank you, but this is the latest.log, right? can you upload the debug.log

**Comment by DerHofnarr** [comment] 2020-10-02 11:14
the whole one is to large (70k+ lines) so i cut something out :D. https://paste.gg/p/anonymous/e116426706b44afe8909651090c6f4c2

if you need the whole log we need to find another upload service :D

**Comment by maxanier** [comment] 2020-10-02 11:19
You can upload it here: https://cloud.maxgb.de/s/gt5EbF9bfWAG9ie

Does creating a new world work?
Can you try this version: https://cloud.maxgb.de/s/97Cg6dLRCEAjP7K

**Comment by DerHofnarr** [comment] 2020-10-02 11:33
OMG... i treid to load my survival world just for fun and it worked. seems like its incompatible with this shader :" https://www.planetminecraft.com/mod/makeup-ultra-fast-shader/ "

i didnt try the second mod or a new world due to this now. If im experience another issue i will come back to you. Thank you really much for the support. Cheers :-)

**Comment by maxanier** [comment] 2020-10-02 11:45
very strange, I also tried reproducing this with the shaderpack you linked but everything works fine.
Did you check if the issue reoccurs if you activate the shaders again?

**Comment by DerHofnarr** [comment] 2020-10-02 11:50
haa.... strange.... everything works fine now. what the hell i didnt changed anything. thats so strange i dont get it lol :D

**Comment by maxanier** [comment] 2020-10-02 11:53
somebody else has a similar issue so something really weird is going on here,
anyway glad that it is working fine for you now

**Comment by DerHofnarr** [comment] 2020-10-02 11:57
yep im glad too. Maybe the solution was "kick mod> load world > Shaderpack off > close game > add mod > load world > shaderpack on" ? but anyways i appriciate your help :+1: :)

**Comment by maxanier** [comment] 2020-10-04 15:06
Yes, seems to be in issue with Optifine. You must not start the game with shaders enabled.
However, you can enable shaders after the game has started

**Comment by maxanier** [comment] 2020-11-21 20:09
Witht the lastest Optifine (G5) the game does not crash anymore, but world gen is still broken. E.g. vampire forest does not have any trees

**Comment by maxanier** [comment] 2021-01-21 21:15
Forgot to close this. Optifine G6 has fixed the remaining issues

**Closed as completed by maxanier** 2021-01-21 21:15 UTC
Labels: bug, external, 1.16
