### ISSUE TITLE
Crash with GuideAPI 2.1.7-62

### ISSUE THREAD

**Issue by LemADEC** [TeamLapen/Vampirism#340] opened 2018-08-14 08:43 UTC
## Versions
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.4.2749-universal.jar
- Vampirism: 1.12.2-1.4.4
guide-api: Guide-API-1.12-2.1.7-62.jar

## Issue Description
Client crash when using the guide book

## Reproduce Steps
- open the guide in Items > Hunter coat > page 7

## Additional Information
https://paste.dimdev.org/tixoguwuni.mccrash

```
java.lang.NoSuchMethodError: amerifrance.guideapi.gui.GuiBase.drawSplitString(Ljava/lang/String;IIII)V
    at de.teamlapen.vampirism.modcompat.guide.pages.BasicWeaponTableRecipeRenderer.draw(BasicWeaponTableRecipeRenderer.java:96)
    at de.teamlapen.vampirism.modcompat.guide.pages.ShapedWeaponTableRecipeRenderer.draw(ShapedWeaponTableRecipeRenderer.java:25)
    at de.teamlapen.vampirism.modcompat.guide.pages.PageRecipe.draw(PageRecipe.java:36)
    at amerifrance.guideapi.wrapper.PageWrapper.draw(PageWrapper.java:50)
    at amerifrance.guideapi.gui.GuiEntry.drawScreen(GuiEntry.java:82)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:381)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1124)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1118)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3940)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by maxanier** [comment] 2018-08-14 09:51
This is a duplicate of #325.
It is fixed, but I haven't pushed a fixed release yet. For now downgrade to GuideAPI- ****-60 or below if  possible.
Anyway, thanks for reporting

**Closed as completed by maxanier** 2018-08-14 09:51 UTC
Labels: duplicate
