### ISSUE TITLE
Crash in multiplayer [Bug]

### ISSUE THREAD

**Issue by Taknax** [TeamLapen/Vampirism#812] opened 2020-11-30 17:18 UTC
Server thread/WARN [vampirism]: [EntityEventHandler]Could not replace zombie target task

**Comment by maxanier** [comment] 2020-11-30 19:44
A) pretty sure this is not a crash, it is probably logged because another mod messes with zombie AI. the game should work fine, however, zombies might attack vampires.
B) please provide a crash log, if it actually is one
C) Don't delete the form when creating an issue but fill it in

**Comment by Taknax** [comment] 2020-12-01 09:00
Ty for reply and this beautiful mod. Im gonna check and try to fix.

Is it possible the issue is come fron champions mod? It tieres the mobs.

**Comment by Taknax** [comment] 2020-12-05 00:56
Now i have crash report after fighting a wizard from the Wizardry mod. I didnt understand how a wizardry mod can influence vampirism?
I figured out that IPixelies Gender Mod is causing the most trouble. After deleting the issue got better, but not fully gone.

[https://pastebin.com/cT92TAQX](https://pastebin.com/cT92TAQX)

Edit: I tried without Vampirism and the issue was gone.

One log more: [https://pastebin.com/VYXDsTaf](url)

**Comment by maxanier** [comment] 2020-12-07 18:35
Ok, this is a duplicate of #811 then.

**Closed as completed by maxanier** 2020-12-07 18:35 UTC
Labels: bug, duplicate
