### ISSUE TITLE
[Bug]: Bat mode/ Create mod

### ISSUE THREAD

**Issue by XionioXMaster** [TeamLapen/Vampirism#1011] opened 2021-11-23 07:26 UTC
### Minecraft Version

1.16.x

### Forge Version

 36.2.18

### Vampirism Version

1.8.3

### Singleplayer/Multiplayer

Server

### What happened?

I found a deception. If, in bat mode, you use the wrench from the Create mod on something that should drop, it will drop, but it will not disappear on the item that contains the block.
if the autonomous activator is broken like this, the object in his hand also dupes

### Relevant log output

```shell
does not report this situation
```

### Reproduce steps

We take the wrench
we turn into a mouse
press the 2nd mouse button on the block that can be expanded in create
dup it

### Other relevant mods

Create

**Comment by DonorKrovi** [comment] 2021-11-23 07:33
**Damn this is real dupe! I just tested this on my server, add the option to disable some item for the bat**

**Comment by XionioXMaster** [comment] 2021-11-23 10:29
It turned out really awkward, now everyone is duping on my server, and I probably need to wait for a fix for about a month

**Comment by GionoJiara** [comment] 2021-11-23 10:30
> It turned out really awkward, now everyone is duping on my server, and I probably need to wait for a fix for about a month
I have the same problem, I cannot delete Create for the sake of this mod, I wonder when will it be fixed

**Comment by maxanier** [comment] 2021-11-23 14:13
Your best bet probably is to deactivate the bat action (in balance config) until this is fixed

**Comment by maxanier** [comment] 2021-11-24 08:22
I have identified the cause of this issue. However, I am not yet sure, what the best fix for this is.
In the meantime, please stick with my suggestion above.

**Comment by maxanier** [comment] 2021-11-24 22:31
Fixed in 1.8.4.
Although, I think this is an issue in Create or a design issue in Forge

**Closed** 2021-11-24 22:31 UTC
Labels: bug, modcompat, 1.16
