### ISSUE TITLE
[Bug]: Cannot get Vampire player capability from player ClientPlayerEntity

### ISSUE THREAD

**Issue by YTYT233** [TeamLapen/Vampirism#1101] opened 2022-07-02 10:28 UTC
### Minecraft Version

1.16.x

### Forge Version

36.2.4

### Vampirism Version

1.8.3

### Singleplayer/Multiplayer

Singleplayer

### What happened?

it starts fine until player firstly die and cause the issue that the minecraft client shows a normal "dead menu " and soon it gets "saving world" and get crashed .  Then I restart minecraft without any changes to load that world ,the same thing happened again.idk which mod cause this crash the NEC(not enough crash) didn't give a direct mod. In crash log , i can find a line  

the following is the crash log ,sorry about my poor ENGLISH.

### Relevant log output

```shell
---- Minecraft Crash Report ----
// My bad.

Time: 22-7-2 下午5:32
Description: Unexpected error

java.lang.IllegalStateException: Cannot get Vampire player capability from player ClientPlayerEntity['yzh233'/116, l='ClientLevel', x=88.81, y=63.00, z=-933.15]
	at de.teamlapen.vampirism.player.vampire.VampirePlayer.lambda$get$0(VampirePlayer.java:120) ~[vampirism:1.8.8] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:296) ~[forge:?] {re:classloading}
	at de.teamlapen.vampirism.player.vampire.VampirePlayer.get(VampirePlayer.java:120) ~[vampirism:1.8.8] {re:classloading}
	at tfar.classicbar.overlays.mod.Blood.renderBar(Blood.java:41) ~[classicbar:4.1.0-1.16.5] {re:classloading}
	at tfar.classicbar.EventHandler.lambda$renderBars$3(EventHandler.java:66) ~[classicbar:4.1.0-1.16.5] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_311] {}
	at tfar.classicbar.EventHandler.renderBars(EventHandler.java:65) ~[classicbar:4.1.0-1.16.5] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_772_EventHandler_renderBars_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.pre(ForgeIngameGui.java:828) ~[forge:?] {re:mixin,xf:fml:xaerominimap:xaero_forgeingamegui_render,re:classloading,xf:fml:xaerominimap:xaero_forgeingamegui_render,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FrameCounterMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:121) ~[forge:?] {re:mixin,xf:fml:xaerominimap:xaero_forgeingamegui_render,re:classloading,xf:fml:xaerominimap:xaero_forgeingamegui_render,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FrameCounterMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:472) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:rubidium.mixins.json:core.matrix.MixinGameRenderer,pl:mixin:APP:magnesium_extras.mixins.json:TotalDarkness.MixinGameRenderer,pl:mixin:APP:magnesium_extras.mixins.json:Zoom.GameRendererMixin,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:977) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-Forge_36.2.34.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.teamlapen.vampirism.player.vampire.VampirePlayer.lambda$get$0(VampirePlayer.java:120) ~[vampirism:1.8.8] {re:classloading}
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:296) ~[forge:?] {re:classloading}
	at de.teamlapen.vampirism.player.vampire.VampirePlayer.get(VampirePlayer.java:120) ~[vampirism:1.8.8] {re:classloading}
	at tfar.classicbar.overlays.mod.Blood.renderBar(Blood.java:41) ~[classicbar:4.1.0-1.16.5] {re:classloading}
	at tfar.classicbar.EventHandler.lambda$renderBars$3(EventHandler.java:66) ~[classicbar:4.1.0-1.16.5] {re:classloading}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_311] {}
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_311] {}
	at tfar.classicbar.EventHandler.renderBars(EventHandler.java:65) ~[classicbar:4.1.0-1.16.5] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_772_EventHandler_renderBars_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.pre(ForgeIngameGui.java:828) ~[forge:?] {re:mixin,xf:fml:xaerominimap:xaero_forgeingamegui_render,re:classloading,xf:fml:xaerominimap:xaero_forgeingamegui_render,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FrameCounterMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:121) ~[forge:?] {re:mixin,xf:fml:xaerominimap:xaero_forgeingamegui_render,re:classloading,xf:fml:xaerominimap:xaero_forgeingamegui_render,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FrameCounterMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: Client Chunk Cache: 16384, 108
	Level dimension: minecraft:overworld
	Level spawn location: World: (-96,69,-128), Chunk: (at 0,4,0 in -6,-8; contains blocks -96,0,-128 to -81,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 15532 game time, 1754 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A,re:classloading,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,xf:fml:xaerominimap:xaero_clientworldclass,pl:mixin:APP:dynamiclightsreforged.mixins.json:ClientWorldMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.world_ticking.MixinClientWorld,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:radon.mixins.json:client.world.MixinClientWorld,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:dynamiclightsreforged.mixins.json:MinecraftClientMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.gui.fast_fps_pie.MixinMinecraftClient,pl:mixin:APP:rubidium.mixins.json:features.options.MixinMinecraftClient,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:magnesium_extras.mixins.json:FrameCounter.FpsAccessorMixin,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5-Forge_36.2.34.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_311] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_311] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_311, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7009387024 bytes (6684 MB) / 9229565952 bytes (8802 MB) up to 9233760256 bytes (8806 MB)
	CPUs: 4
	JVM Flags: 7 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+IgnoreUnrecognizedVMOptions -Xmn256m -Xmx8806m
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		dynamiclightsreforged-mc1.16.5_v1.0.1.j|Dynamic Lights Reforged       |dynamiclightsreforged         |mc1.16.5_v1.0.1     |DONE      |Manifest: NOSIGNATURE
		QuarkOddities-1.16.3.jar                |Quark Oddities                |quarkoddities                 |1.16.3              |DONE      |Manifest: NOSIGNATURE
		notenoughcrashes-4.1.4+1.16.5-forge.jar    |Not Enough Crashes            |notenoughcrashes              |4.1.4+1.16.5        |DONE      |Manifest: NOSIGNATURE
		TRansliterationLib-1.0.4.jar                      |TRansliterationLib Mod        |transliterationlib            |1.0.4               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.152.jar               |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE
		VisualWorkbench-v1.1.0-1.16.5.jar                 |Visual Workbench              |visualworkbench               |1.1.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		AttributeFix-1.16.5-10.1.4.jar             |AttributeFix                  |attributefix                  |10.1.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
	          Mekanism-1.16.5-10.1.2.457.jar             |Mekanism                      |mekanism                      |10.1.2              |DONE      |Manifest: NOSIGNATURE
		 ProjectE-1.16.5-PE1.0.2.jar             |ProjectE                      |projecte                      |PE1.0.2             |DONE      |Manifest: NOSIGNATURE
		MultiMine-1.16.5.jar                       |Multi Mine                    |multimine                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		 ae2extras-1.3.1-1.16.5.jar                |AE2 Extras                    |ae2extras                     |1.3.1-1.16.5        |DONE      |Manifest: NOSIGNATURE
		rubidium-0.2.7.jar                            |Rubidium                      |rubidium                      |0.2.7               |DONE      |Manifest: NOSIGNATURE
		Guide-API-VP-1.16.5-2.2.2.jar                     |Guide-API VP                  |guideapi-vp                   |2.2.2               |DONE      |Manifest: NOSIGNATURE
		 Neat 1.7-27.jar                          |Neat                          |neat                          |1.7-27              |DONE      |Manifest: NOSIGNATURE
		MerchantMarkers-1.16.5-1.2.0.jar                  |Merchant Markers              |merchantmarkers               |1.2.0               |DONE      |Manifest: NOSIGNATURE
		FastSuite-1.16.4-1.1.1.jar               |FastSuite                     |fastsuite                     |1.1.1               |DONE      |Manifest: NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                   |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |DONE      |Manifest: NOSIGNATURE
		 shutupexperimentalsettings-1.0.3.jar  |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.3               |DONE      |Manifest: NOSIGNATURE
		 XaerosWorldMap_1.23.3_Forge_1.16.5.ja|Xaero's World Map             |xaeroworldmap                 |1.23.3              |DONE      |Manifest: NOSIGNATURE
		Placebo-1.16.5-4.7.0.jar                          |Placebo                       |placebo                       |4.7.0               |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-8.4.7.jar             |Applied Energistics 2         |appliedenergistics2           |8.4.7               |DONE      |Manifest: 95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		configured-1.5.2-1.16.5.jar                |Configured                    |configured                    |1.5.2               |DONE      |Manifest: NOSIGNATURE
		ItemBorders-1.16.5-1.1.6.jar                      |Item Borders                  |itemborders                   |1.1.6               |DONE      |Manifest: NOSIGNATURE
		good-nights-sleep-1.16.5-1.2.14.jar  |Good Night's Sleep            |good_nights_sleep             |1.2.14              |DONE      |Manifest: NOSIGNATURE
		randompatches-2.4.4-forge.jar                     |RandomPatches                 |randompatches                 |2.4.4-forge         |DONE      |Manifest: 92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		lazydfu-0.1.3.jar                       |LazyDFU                       |lazydfu                       |0.1.3               |DONE      |Manifest: NOSIGNATURE
		projecte-integration-1.16.5-4.4.4.jar             |ProjectE Integration          |projecteintegration           |4.4.4               |DONE      |Manifest: NOSIGNATURE
		farsight-1.7.jar                                  |Farsight mod                  |farsight_view                 |1.7                 |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.1.2.457.jar|Mekanism: Generators          |mekanismgenerators            |10.1.2              |DONE      |Manifest: NOSIGNATURE
		KAIMyEntity-1.4b14.jar  |KAIMyEntity                   |kaimyentity                   |1.4b14              |DONE      |Manifest: NOSIGNATURE
		dynviewdist-2.0.jar                               |Dynamic view distance         |dynview                       |1.8                 |DONE      |Manifest: NOSIGNATURE
		[magnesium_extras-mc1.16.5_v1.3.1.jar     |Magnesium Extras              |magnesium_extras              |mc1.16.5_v1.3.1     |DONE      |Manifest: NOSIGNATURE
		FpsReducer-forge-1.24-mc1.16.5.jar       |FPS Reducer                   |fpsreducer                    |1.24-mc1.16.5       |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		DynamicSurroundings-1.16.5-4.0.5.0.jar            |§3Dynamic Surroundings        |dsurround                     |4.0.5.0             |DONE      |Manifest: NOSIGNATURE
		EquipmentCompare-1.16.5-1.2.7.jar                 |Equipment Compare             |equipmentcompare              |1.2.7               |DONE      |Manifest: NOSIGNATURE
		AdvancementPlaques-1.16.5-1.4.1.jar        |Advancement Plaques           |advancementplaques            |1.4.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		plonk-1.16.5-9.0.8.jar                  |Plonk                         |plonk                         |9.0.8               |DONE      |Manifest: NOSIGNATURE
		radon-0.8.0a.jar                              |Radon                         |radon                         |0.8.0a              |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-2.14-mc1.16.2.jar              |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |Manifest: NOSIGNATURE
		Psi 1.16-97.jar                                   |Psi                           |psi                           |1.16-96             |DONE      |Manifest: NOSIGNATURE
		MekanismAdditions-1.16.5-10.1.2.457.jar  |Mekanism: Additions           |mekanismadditions             |10.1.2              |DONE      |Manifest: NOSIGNATURE
		Jade-1.16.4-2.8.1.jar                      |Jade                          |jade                          |2.8.1               |DONE      |Manifest: NOSIGNATURE
		EntityCulling-1.16.5-2.1.6.jar         |Entity Culling                |entity_culling                |2.1.6               |DONE      |Manifest: NOSIGNATURE
		ShoulderSurfing-1.16.5-2.2.2.jar         |Shoulder Surfing              |shouldersurfing               |1.16.5-2.2.2        |DONE      |Manifest: NOSIGNATURE
		FirstPersonMod-2.0.1.jar             |FirstPersonModel Mod          |firstpersonmod                |2.0.1               |DONE      |Manifest: NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar          |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |Manifest: NOSIGNATURE
		Highlighter-1.16.5-1.1.1.jar                      |Highlighter                   |highlighter                   |1.1.1               |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.2.jar                             |betterfpsdist mod             |betterfpsdist                 |1.2                 |DONE      |Manifest: NOSIGNATURE
		jeiintegration_1.16.5-7.1.0.22.jar        |JEI Integration               |jeiintegration                |7.1.0.22            |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.16.5-1.0.41.jar                         |Iceberg                       |iceberg                       |1.0.41              |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.3.jar                         |Patchouli                     |patchouli                     |1.16.4-53.3         |DONE      |Manifest: NOSIGNATURE
		LegendaryTooltips-1.16.5-1.1.7.jar                |Legendary Tooltips            |legendarytooltips             |1.1.7               |DONE      |Manifest: NOSIGNATURE
		oculus-1.2.5.jar                                  |Oculus                        |oculus                        |1.2.5               |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.9.3_Forge_1.16.5.jar|Xaero's Minimap               |xaerominimap                  |22.9.3              |DONE      |Manifest: NOSIGNATURE
		FastWorkbench-1.16.5-4.6.1.jar          |Fast Workbench                |fastbench                     |4.6.1               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		Quark-r2.4-322.jar                           |Quark                         |quark                         |r2.4-322            |DONE      |Manifest: NOSIGNATURE
		kryptonreforged-mc1.16.5_v1.0.0.jar     |Krypton Reforged              |kryptonreforged               |mc1.16.5_v1.0.0     |DONE      |Manifest: NOSIGNATURE
		OreExcavation-1.8.157.jar                  |Ore Excavation                |oreexcavation                 |1.8.157             |DONE      |Manifest: e7:68:1c:0d:b9:7e:cf:f8:f3:40:9c:84:c5:39:d7:a4:59:78:b0:6b:c3:fd:b7:4f:69:18:a3:88:e3:76:8c:3f
		FreeCamByKapiteon1.16.5-2.0.jar                   |Freecam by kapiteon           |freecam                       |2.0                 |DONE      |Manifest: NOSIGNATURE
		structurize-1.16.5-1.0.392-RELEASE.jar      |Structurize                   |structurize                   |1.16.5-1.0.392-RELEA|DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.1.2.457.jar      |Mekanism: Tools               |mekanismtools                 |10.1.2              |DONE      |Manifest: NOSIGNATURE
		FastFurnace-1.16.5-4.5.0.jar             |FastFurnace                   |fastfurnace                   |4.5.0               |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.16.5-1.0.858-BETA.jar      |MineColonies                  |minecolonies                  |1.16.5-1.0.858-BETA |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.4.0.jar          |AppleSkin                     |appleskin                     |2.4.0+mc1.16.4      |DONE      |Manifest: NOSIGNATURE
		 helium-1.0.jar                                |Helium                        |helium                        |1.0                 |DONE      |Manifest: NOSIGNATURE
		Vampirism-1.16.5-1.8.8.jar             |Vampirism                     |vampirism                     |1.8.8               |DONE      |Manifest: NOSIGNATURE
	          VampirismIntegrations-1.16.5-1.6.1.jar    |Vampirism Integrations        |vampirism_integrations        |1.6.1               |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.14.64-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.14.64             |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v1.0.15-1.16.5-Forge.jar               |Puzzles Lib                   |puzzleslib                    |1.0.15              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Phi-1.16-2.7.jar                                  |Phi                           |phi                           |1.16-2.7            |DONE      |Manifest: NOSIGNATURE
		ProPlacer-v1.0-1.16.2.jar                  |Pro Placer                    |proplacer                     |1.0                 |DONE      |Manifest: d3:cc:6f:1b:30:87:fa:d9:8f:91:15:20:27:63:95:aa:d5:cb:1b:5b:e6:36:cc:57:20:a9:b3:d4:d5:1a:5d:b8
		classicbar-4.1.0-1.16.5.jar               |Classic Bar                   |classicbar                    |4.1.0-1.16.5        |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-v25.2.jar                  |FastLeafDecay                 |fastleafdecay                 |v25.2               |DONE      |Manifest: NOSIGNATURE
		magipsi-1.16.5-2.0.1.0.jar                        |Magical Psi                   |magipsi                       |1.16.5-2.0.1.0      |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b3f16e93-9bc6-4843-8524-cfc33d620a14
	[Psi] Active spell: None
	Patchouli open book context: n/a
	Suspected Mods: None
	Loaded Shaderpack: (off)
	Launched Version: 1.16.5-Forge_36.2.34
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 620 GL version 4.6.0 - Build 30.0.101.1631, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/Minecraft-Mod-Language-Modpack-1-16.zip
	Current Language: 简体中文 (中国)
	CPU: 4x Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
```

### Reproduce steps

1.start minecraft 
2.generate a new world 
3.get died
4.crash

### Other relevant mods

kaimyentity-used to change player models as mmd models

**Comment by Cheaterpaul** [comment] 2022-07-02 10:57
Duplicate of #985

**Closed as completed by Cheaterpaul** 2022-07-02 10:57 UTC
Labels: bug

**Comment by Cheaterpaul** [comment] 2022-07-02 10:59
This issue is known to us and caused by Classic Bar.
There is a fix pending https://github.com/Tfarcenim/ClassicBar/pull/84 since august 2021 so i presume they do not want to fix this problem
