### ISSUE TITLE
Vampirism and RTG integration crash

### ISSUE THREAD

**Issue by touhouzun** [TeamLapen/Vampirism#248] opened 2017-12-08 01:18 UTC
## Versions
- Minecraft:1.10.2                    
- Forge:1.10.2-12.18.3.2511                       
- Vampirism:1.10.2-1.2.4release                                             
- RTG:1.10.2-4.2.0.0-snapshot-5

## Issue Description
With RTG and Vampirism only,game simply crashes on startup.

## Reproduce Steps
1.Put only RTG-1.10.2-4.2.0.0-snapshot5 and Vampirism-1.10.2-1.2.4 in the mod folder
2.Start up your launcher
3.Wait for the annoying crash at about 5/7

## Additional Information
Pastbin isn't available so...ctrl+c&ctrl+v instead._(:з)∠)_
[crash-2017-12-06_15.12.47-client.txt](https://github.com/TeamLapen/Vampirism/files/1541081/crash-2017-12-06_15.12.47-client.txt)
I know what the issue is.RTG tried to get its realistic version of your vampireForest biome but couldn't.
"at rtg.world.biome.realistic.vampirism.RealisticBiomeVAMPVampireForest.<clinit>(RealisticBiomeVAMPVampireForest.java:25)"
However...RTG-4.2.0.0-snapshot-5's changelog:
"IMPORTANT NOTE 3: This snapshot is meant for TESTING PURPOSES ONLY."
"This snapshot includes changes that were made in the previous snapshots:

4.2.0.0-snapshot-1
4.2.0.0-snapshot-2
4.2.0.0-snapshot-3
4.2.0.0-snapshot-4"
And here is 4.2.0.0-snapshot-1's
"Biome support

Added biome support for ATG (requires Geographicraft or BiomeTweaker to be installed - example BiomeTweaker tweaks for ATG can be found here ).
Added biome support for Floricraft.
Added biome support for Ice and Fire.
Added biome support for Vampirism."
In theory your mod should be auto-supported.Should I copy my issue to Team-RTG as well?
(p.s. I posted an issue days or months ago:when RTG and Heat&Climate are installed, the cave&ravine generation seemed vanilla-style,densed and lost control,but I failed._(:з)∠)_Just complaining myself,never mind.)

**Comment by touhouzun** [comment] 2017-12-08 04:51
By the way,I'm not good at writing English.Sorry for my grammar and spelling issue._(:з)∠)_

**Comment by maxanier** [comment] 2017-12-08 20:32
Unfortunately, Vampirism 1.2.x does not work with RTG 4.2 (and probably never will). Both sides messed up a little bit.
One solution is to use Vampirism 1.1.x, sorry about that.

Duplicate of https://github.com/TeamLapen/Vampirism/issues/234

**Closed as completed by maxanier** 2017-12-08 20:32 UTC
Labels: duplicate

**Comment by touhouzun** [comment] 2017-12-09 05:10
Ok I didn't realise it.Thanks.
