### ISSUE TITLE
[Bug] Players have cured themselves of Vampirism and can no longer spawn at beds.

### ISSUE THREAD

**Issue by AniraSnowMew** [TeamLapen/Vampirism#674] opened 2020-04-24 03:43 UTC
## Versions
- Minecraft:   1.12.2                  
- Forge:  14.23.5.2387     with Spongeforge 12.2-2838-7.2.0         
- Vampirism:    1.6.2                                         

## Issue Description
 
One of my players accidently became a vampire, at first they accepted it and made the coffin to sleep in. eventually they managed to cure themselves via the Altar of Cleansing thus removing their ability to use the coffin that had become their new spawn point. when they died from using the altar it sent them back to world spawn. They used slash home to get back to their base to try and reset their spawn and after resetting their spawn to their bed they thought they were good. however the next time they died they were again sent back to world spawn. we tried various methods to try and get a bed spawn point to take but no bed spawns would take. 

I tried to replicate this and didn't even have to use a coffin to replicate the issue. the moment I cured myself via an altar to return human I was no longer able to properly bind myself to a bed spawn point. I have not tried to replicate the issue using a vampire hunter turned human again via the altar but I have a feeling the results might be the same.

## Reproduce Steps

Have a respawn point set that is tied to a bed
Become a vampire (will possibly work with vampire hunters as well)
Use an Alter of Cleansing to return yourself to being a human, and die because of it, or die afterwards if in creative mode when cured.
Get sent back world spawn, 
Try to use a bed to set your respawn point
Die and get sent back to world spawn again.

## Additional Information

I have since found through trouble shooting, that part of the issue is that when the issue occurs it seems to be made worse by the fact that nucleus has the following in their default configurations 
"By default, Nucleus overrides respawning such that sleeping in a bed does not change a player’s respawn location.  If you wish to let players sleep in beds to set their own spawn position, set spawn.affect-bed-spawn to false in main.conf and reload the config. Nucleus will then ignore any event that respawns the player next to their bed."

 I am not sure if Vampirism is set to actually attempt to rewrite the spawn point after they use the altar, or if it simply deletes it, but seeing as players were able to respawn at their beds even with nucleus' default behavior prior to using the  altar I can only imagine Vampirism still has some part to play.

**Comment by Cheaterpaul** [comment] 2020-04-24 15:20
I cannot reproduce this with the given steps. And i dont see a reason for this with Vampirism, because the interacting with the altar just attacks you with DamageType#MAGIC 

https://github.com/TeamLapen/Vampirism/blob/88b8d696fca536d9889923a97d76e8458a81ebdf/src/main/java/de/teamlapen/vampirism/network/InputEventPacket.java#L203

With that information i would assume Nucleus cause the problem.

**Comment by maxanier** [comment] 2020-04-26 12:45
Vampirism only messes with the spawn point (EntityPlayer#bedLocation) if you try to sleep in a coffin. If you sleep in a bed it should get overridden.
I don't know what Nucleus does, but I currently have no idea how Vampirism is involved.

**Comment by maxanier** [comment] 2020-06-04 09:19
I am sorry but I don't think there is much we can do about this.
Sponge+Nucleus make it hard to debug the cause and as Vampirism does not really affect the spawn point much I don't know where to start looking.
Therefore, I am going to close this.

You could raise a issue with Sponge or with Nucleus as they are likely modifying the spawn code.

**Closed as completed by maxanier** 2020-06-04 09:19 UTC
Labels: bug, 1.12, unconfirmed
