### ISSUE TITLE
[Bug]:  potions dont count vampires as undead

### ISSUE THREAD

**Issue by kaboom24** [TeamLapen/Vampirism#1310] opened 2024-01-02 19:50 UTC
### Minecraft Version

1.20.x

### Forge Version

47.2.0

### Vampirism Version

1.10.1

### Singleplayer/Multiplayer

Singleplayer

### What happened?

so I was watching a vampire hunter attack a advanced vampire but I had a feeling it was losing since it was just a ordinary hunter attacking sinister solace so I figured since vampires are undead ill throw some healing potions on it to damage it but the healing potions healed it undead are supposed to be healed by harming potions and poison potions should act as regen and they are supposed to be harmed by healing potions and regen potions are supposed to act like poison to them and vampires are undead not living could you fix that

### Reproduce steps

1. Load singleplayer world
2. spawn vampire
3. throw healing potion on it

**Comment by Cheaterpaul** [comment] 2024-01-03 11:22
Duplicate of #770

Vampire players are not considered undead. Otherwise the game is very unbalanced, considering features like Smite

**Closed as completed by Cheaterpaul** 2024-01-03 11:22 UTC
Labels: bug, unconfirmed
