### ISSUE TITLE
Can only seem to place coffin in certain spots.

### ISSUE THREAD

**Issue by macks2008** [TeamLapen/Vampirism#156] opened 2017-04-08 00:48 UTC
I'm not sure if I'm doing something wrong, but I can't seem to move the coffin i made for myself anywhere other than where I initially put it when I made it. It's acting like there's something blocking it or something? The place I'm trying to put it looks qualified for a bed, so is there something different about the coffin besides inverted function?
I'll provide screenshots in a few minutes of where I was trying to put it and where I have it currently.

**Comment by macks2008** [comment] 2017-04-08 00:54
![2017-04-07_20 53 00](https://cloud.githubusercontent.com/assets/7110033/24824115/57cd60b0-1bd4-11e7-810c-dab27d5b02b1.png)
![2017-04-07_20 53 29](https://cloud.githubusercontent.com/assets/7110033/24824116/57d87b08-1bd4-11e7-8769-d31a29edf6c4.png)

**Comment by macks2008** [comment] 2017-04-08 19:08
I would really appreciate a response on this. It's extremely annoying, as I'd really like to move my "bed" out of the middle of my mineshaft. While I wait, I have another issue to open (assuming I don't find that someone has already opened one) concerning the "blood container". See you there, I hope...

**Comment by maxanier** [comment] 2017-04-09 07:55
That is strange. So there are only very few spots where you can place the coffin or are there just certain spots not working?
Does placing a vanilla bed work at the same spot?
I also need to know the version of Vampirism you are using.

**Comment by macks2008** [comment] 2017-04-12 23:05
I can't seem to place the coffin anywhere except where I placed it initially. I'll try a vanilla bed and check the version and report back in about 5 minutes, maybe?

**Comment by macks2008** [comment] 2017-04-12 23:09
vanilla beds place fine. The version is 1.1.0-beta.1
rail craft is installed, so is it possible RC's godforsaken "residual heat" tile entities are interfering? I would have to open the world in MCE to be sure, but I suspect there might be tile entities in the way. That's my best guess anyway. Let me look into it and I'll report back again

**Comment by macks2008** [comment] 2017-04-12 23:39
Nope, doesn't look like there's any tile entities in the way. I assume vampirism:blockCoffin inherits from minecraft:bed, so what could you have possibly changed to break it??

**Comment by maxanier** [comment] 2017-04-18 15:29
Sorry, somehow did not save my answer from a few days ago.
Neither the coffin nor the item are inheriting from the vanilla classes, but they work very similar.

If there is no tile-entity in the way, I'm not sure what exactly is causing this issue. If this still exists, I will create a specific version for you, which logs what is happening verbose. Maybe we can find the cause that way.

**Comment by maxanier** [comment] 2017-04-23 11:33
OK, I  think I found the issue, was quite a stupid mistake I made a while ago.
Same as #160 . Will be fixed in the next version.
Thx for reporting :)

**Closed** 2017-04-23 14:13 UTC
Labels: bug
