### ISSUE TITLE
Blood Vision not working properly

### ISSUE THREAD

**Issue by THEAN24** [TeamLapen/Vampirism#670] opened 2020-04-18 12:50 UTC
## Versions
- Minecraft: 1.15.2                   
- Forge: 31.1.46                      
- Vampirism: 1.6.0 alpha                                            

## Issue Description
When ever I use the blood vision it seems that there are small dots at the upper right corner and no mobs are appearing during blood vision.

## Reproduce Steps
Go to a village and use blood vision

https://drive.google.com/file/d/1DuE4dfik1KxDx6hvQIHmjh5rKBoyrGU9/view?usp=sharing
## Additional Information
Mods Used:
Angelring
Baubles
Caelus Forge
Cofh core
Cucumber
Curios 
ForgeCuriouselytra Forge
CyclopsCore
DimStorage
Ensorcellation
Everlasting Abilities
ExtraDisk
FL
Flux
Flux Networks
Forbidden Arcanus
Gobber Forge
Gravestone
Industrial Foregoing
JEI
Mcjtylib
MysticalAgradditions
MysticalAgriculture
MysticalCustomization
refined storage
rftool builder
= power
= utility
Solar Flux Reborn
one probe
thutcore
thuttech
titanium
Vampire Need Umbrellas
Vampirism
Water Strainer
World Edit
Xaeros Minimap
Xnet

**Comment by maxanier** [comment] 2020-04-18 14:52
Duplicate of https://github.com/TeamLapen/Vampirism/issues/665

**Closed as completed by maxanier** 2020-04-18 14:52 UTC
Labels: bug, duplicate, unconfirmed
