### ISSUE TITLE
the game crash on world start up/be maked

### ISSUE THREAD

**Issue by tech-boy101** [TeamLapen/Vampirism#74] opened 2016-05-26 15:09 UTC
ok so this mod crash if you start a new world in survival or if in creative and go survival and cure you seft of vampirism or hunter one it will crash on it and you will all way crash on try re load the world

**Comment by tech-boy101** [comment] 2016-05-26 15:17
ps you dont crash in go creative turn in to a vampire or hunter then go in to survical

**Comment by maxanier** [comment] 2016-05-28 08:46
Can you please provide a crash report for this. I'm not able to reproduce this issue

**Comment by tech-boy101** [comment] 2016-05-28 18:07
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.1.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 5/28/16 1:07 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at de.teamlapen.vampirism.entity.factions.PredicateFaction.apply(PredicateFaction.java:61)
	at de.teamlapen.vampirism.entity.factions.PredicateFaction.apply(PredicateFaction.java:17)
	at net.minecraft.entity.ai.EntityAINearestAttackableTarget$1.apply(SourceFile:53)
	at net.minecraft.entity.ai.EntityAINearestAttackableTarget$1.apply(SourceFile:47)
	at net.minecraft.world.World.func_184150_a(World.java:3327)
	at net.minecraft.entity.ai.EntityAINearestAttackableTarget.func_75250_a(SourceFile:72)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2146)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:570)
	at de.teamlapen.vampirism.entity.EntityVampirism.func_70636_d(EntityVampirism.java:169)
	at de.teamlapen.vampirism.entity.vampire.EntityVampireBase.func_70636_d(EntityVampireBase.java:123)
	at de.teamlapen.vampirism.entity.vampire.EntityBasicVampire.func_70636_d(EntityBasicVampire.java:111)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:299)
	at de.teamlapen.vampirism.entity.EntityVampirism.func_70071_h_(EntityVampirism.java:174)
	at de.teamlapen.vampirism.entity.vampire.EntityBasicVampire.func_70071_h_(EntityBasicVampire.java:119)
	at net.minecraft.world.World.func_72866_a(World.java:1940)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1909)
	at net.minecraft.world.World.func_72939_s(World.java:1743)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at de.teamlapen.vampirism.entity.factions.PredicateFaction.apply(PredicateFaction.java:61)
	at de.teamlapen.vampirism.entity.factions.PredicateFaction.apply(PredicateFaction.java:17)
	at net.minecraft.entity.ai.EntityAINearestAttackableTarget$1.apply(SourceFile:53)
	at net.minecraft.entity.ai.EntityAINearestAttackableTarget$1.apply(SourceFile:47)
	at net.minecraft.world.World.func_184150_a(World.java:3327)
	at net.minecraft.entity.ai.EntityAINearestAttackableTarget.func_75250_a(SourceFile:72)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:94)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2146)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:570)
	at de.teamlapen.vampirism.entity.EntityVampirism.func_70636_d(EntityVampirism.java:169)
	at de.teamlapen.vampirism.entity.vampire.EntityVampireBase.func_70636_d(EntityVampireBase.java:123)
	at de.teamlapen.vampirism.entity.vampire.EntityBasicVampire.func_70636_d(EntityBasicVampire.java:111)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1976)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:299)
	at de.teamlapen.vampirism.entity.EntityVampirism.func_70071_h_(EntityVampirism.java:174)
	at de.teamlapen.vampirism.entity.vampire.EntityBasicVampire.func_70071_h_(EntityBasicVampire.java:119)
	at net.minecraft.world.World.func_72866_a(World.java:1940)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1909)

-- Entity being ticked --
Details:
	Entity Type: vampirism.vampire (de.teamlapen.vampirism.entity.vampire.EntityBasicVampire)
	Entity ID: 3877
	Entity Name: Vampire
	Entity's Exact location: 123.50, 43.00, 221.50
	Entity's Block location: World: (123,43,221), Chunk: (at 11,2,13 in 7,13; contains blocks 112,0,208 to 127,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1743)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['0techboy0'/795, l='New World', x=206.50, y=60.00, z=205.50]]
	Chunk stats: ServerChunkCache: 566 Drop: 0
	Level seed: 5941558964362831867
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (212,64,212), Chunk: (at 4,4,4 in 13,13; contains blocks 208,0,208 to 223,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 13 game time, 13 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 31829 (now: false), thunder time: 172236 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:148)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 749326120 bytes (714 MB) / 1557790720 bytes (1485 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.28 Powered by Forge 12.17.0.1921 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1921-1.9.4.jar) 
	UCHIJAAAA	Forge{12.17.0.1921} [Minecraft Forge] (forge-1.9.4-12.17.0.1921-1.9.4.jar) 
	UCHIJAAAA	JEI{3.4.0.204} [Just Enough Items] (jei_1.9.4-3.4.0.204.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.0-39} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.0-39 - Copy.jar) 
	UCHIJAAAA	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9.4-1.4.1.jar) 
	UCHIJAAAA	cyclopscore{0.6.3} [Cyclops Core] (CyclopsCore-1.9.4-0.6.3.jar) 
	UCHIJAAAA	evilcraft{0.10.2} [EvilCraft] (EvilCraft-1.9.4-0.10.2.jar) 
	UCHIJAAAA	fe{1.2.1} [Food Expansion] (FoodExpansion1.2.1-1.9.4 - Copy.jar) 
	UCHIJAAAA	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9.4-1.8.jar) 
	UCHIJAAAA	lycanitesmobs{1.14.1.1 - MC 1.9.4} [Lycanites Mobs] (LycanitesMobsComplete 1.14.1.1 [1.9.4].jar) 
	UCHIJAAAA	arcticmobs{1.14.1.1 - MC 1.9.4} [Lycanites Arctic Mobs] (LycanitesMobsComplete 1.14.1.1 [1.9.4].jar) 
	UCHIJAAAA	demonmobs{1.14.1.1 - MC 1.9.4} [Lycanites Demon Mobs] (LycanitesMobsComplete 1.14.1.1 [1.9.4].jar) 
	UCHIJAAAA	desertmobs{1.14.1.1 - MC 1.9.4} [Lycanites Desert Mobs] (LycanitesMobsComplete 1.14.1.1 [1.9.4].jar) 
	UCHIJAAAA	forestmobs{1.14.1.1 - MC 1.9.4} [Lycanites Forest Mobs] (LycanitesMobsComplete 1.14.1.1 [1.9.4].jar) 
	UCHIJAAAA	freshwatermobs{1.14.1.1 - MC 1.9.4} [Lycanites Freshwater Mobs] (LycanitesMobsComplete 1.14.1.1 [1.9.4].jar) 
	UCHIJAAAA	infernomobs{1.14.1.1 - MC 1.9.4} [Lycanites Inferno Mobs] (LycanitesMobsComplete 1.14.1.1 [1.9.4].jar) 
	UCHIJAAAA	junglemobs{1.14.1.1 - MC 1.9.4} [Lycanites Jungle Mobs] (LycanitesMobsComplete 1.14.1.1 [1.9.4].jar) 
	UCHIJAAAA	mountainmobs{1.14.1.1 - MC 1.9.4} [Lycanites Mountain Mobs] (LycanitesMobsComplete 1.14.1.1 [1.9.4].jar) 
	UCHIJAAAA	plainsmobs{1.14.1.1 - MC 1.9.4} [Lycanites Plains Mobs] (LycanitesMobsComplete 1.14.1.1 [1.9.4].jar) 
	UCHIJAAAA	saltwatermobs{1.14.1.1 - MC 1.9.4} [Lycanites Saltwater Mobs] (LycanitesMobsComplete 1.14.1.1 [1.9.4].jar) 
	UCHIJAAAA	shadowmobs{1.14.1.1 - MC 1.9.4} [Lycanites Shadow Mobs] (LycanitesMobsComplete 1.14.1.1 [1.9.4].jar) 
	UCHIJAAAA	swampmobs{1.14.1.1 - MC 1.9.4} [Lycanites Swamp Mobs] (LycanitesMobsComplete 1.14.1.1 [1.9.4].jar) 
	UCHIJAAAA	Psi{beta-33} [Psi] (Psi-beta-33.jar) 
	UCHIJAAAA	randomthings{3.7.1} [Random Things] (RandomThings-MC1.9.4-3.7.1.jar) 
	UCHIJAAAA	rftools{4.49} [RFTools] (rftools-1.9.4-4.49.jar) 
	UCHIJAAAA	rftoolsdim{4.23beta40} [RFTools Dimensions] (rftoolsdim-1.9.4-4.23beta40.jar) 
	UCHIJAAAA	vampirism{1.0.0-Alpha+05-25-17-15} [Vampirism] (Vampirism-1.9.4-1.0.0-Alpha+05-25-17-15.jar) 
	UCHIJAAAA	teamlapen-lib{1.0.0-Alpha+05-25-17-15} [TeamLapen Library] (Vampirism-1.9.4-1.0.0-Alpha+05-25-17-15.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.9.4-3.7.1.jar)
  lumien.randomthings.asm.ClassTransformer
LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['0techboy0'/795, l='New World', x=206.50, y=60.00, z=205.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by tech-boy101** [comment] 2016-05-28 18:08
there

**Comment by maxanier** [comment] 2016-05-28 18:32
Thanks.

This crash should be fixed in the newest update: http://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2303363

**Comment by tech-boy101** [comment] 2016-05-29 18:08
ok thx hey can i ake you some in on your mod will be change the reagen power and work on blood bar so work better with minecraft 1.9 and up becruse the reagen power i think the reagen power need be like wind you eat a lot porkcrop and hp reagen a lot but take you blood bar way faster by make the blood bar drops in to that thing that left you reagen faster

**Comment by maxanier** [comment] 2016-05-30 07:13
Can you try to word that differently, I'm not sure what you mean :/

**Comment by tech-boy101** [comment] 2016-05-30 20:02
sorry about that i cant spell good like nomal guy but saturation bar in
nomal minecraft give you good regen wind you have some saturation on you
but you dont get this effect wind you vampire power so my ideal is that
that regen power of your can be come power that full you saturation this so
get good regen power and it all so make you hunger to so ye how think about
it

**Comment by maxanier** [comment] 2016-05-30 21:06
Still not exactly sure what you mean.
Do you mean
1. The regeneration skill, that a vampire player can learn, should also regenerate the blood bar.
2. Normal regeneration (when your blood bar is full, and you regain health), should decrease the blood bar faster.
3. Drinking lots of blood also regenerates you health a little bit.
4. A skill that immediately fills your blood bar.
5. Something else?

**Comment by tech-boy101** [comment] 2016-05-30 21:44
something else ok have you play minecraft 1.9.4

**Comment by tech-boy101** [comment] 2016-05-30 21:48
if still cant understend me then is there way for me to talk to you

**Comment by maxanier** [comment] 2016-06-02 15:34
I haven't played it much, but I've played 1.9 a bit.

Mhh. Maybe there is someone you know who can phrase it differently. If you can speak German, you could write in German.

**Closed** 2016-06-19 12:06 UTC
