### ISSUE TITLE
[Bug]: Hunter looks all the same

### ISSUE THREAD

**Issue by 5A93** [TeamLapen/Vampirism#1318] opened 2024-01-07 04:48 UTC
### Minecraft Version

1.19.2

### Forge Version

43.3.7

### Vampirism Version

1.9.5

### Singleplayer/Multiplayer

Singleplayer

### What happened?

While playing I notice all the hunters spawn in my world looks only two types(later I found out it's the base type and hunter 1). Then I tested it in my creative world, trying to use spawn eggs, naming and changing biome but it's no use. Then I checked wiki and tutorial book but there are no explaination for why this will happened, so I try to delete the codename hunter 1 texture. It works this time, but stick to that texture once more. Please tell me if I do anything wrong.
I also notice unlike the vampire minion, hunter minion can't really change there appearance and it seems a little bit unfair, so I recommend you guys to give some more love to the other faction that didn't make it into mod titile.

**Comment by Cheaterpaul** [comment] 2024-01-08 14:03
Duplicate of #1255

**Comment by Cheaterpaul** [comment] 2024-01-08 14:03
fixed in 1.19.4+

**Closed as completed by Cheaterpaul** 2024-01-08 14:03 UTC
Labels: bug, unconfirmed

**Comment by 5A93** [comment] 2024-01-08 14:10
> fixed in 1.19.4+

Do I have anyway to fix it in 1.19.2?

**Comment by Cheaterpaul** [comment] 2024-01-08 16:49
Apart from using 1.19.4 or newer, no.
