### ISSUE TITLE
Error occured at 1.12.2 ...2854 [Bug]

### ISSUE THREAD

**Issue by Taknax** [TeamLapen/Vampirism#811] opened 2020-11-20 10:45 UTC
Their is a bug on my modpack. Game crashed.

https://pastebin.com/9QiWDV3b

**Comment by maxanier** [comment] 2020-11-21 20:07
Can you provide more context?
Does this occur frequently, sometimes, just once? What were you doing at that point.
Seems like some mod is somehow messing with the sleep system

Dev Note:
Nullpointer here: https://github.com/TeamLapen/Vampirism/blob/7a057f6666b22da19bead370caaeeee6fd11e169/src/main/java/de/teamlapen/vampirism/client/core/ClientEventHandler.java#L70

**Comment by Taknax** [comment] 2020-11-22 20:51
it happen when i got attacked by vampires in the vampireforest. I have morpheus intalled for sleep voting and Opticmanager tp longer the daytime 2x.

**Comment by maxanier** [comment] 2020-12-07 18:36
This can probably be fixed on our end even though it is likely that some other mod is the root cause.
However, it might take some time until the next version is released

**Comment by Taknax** [comment] 2020-12-16 11:51
Ty for considering and this awesome mod!

**Comment by CreativeMD** [comment] 2020-12-16 16:44
This is an issue from PlayerRevive (https://github.com/CreativeMD/PlayerRevive/issues/54). It fakes a player to lay in the bed to make the lay animation work. Sorry for the mess :|

**Comment by maxanier** [comment] 2020-12-18 22:38
Thank you for narrowing it down and identifying the root cause!

@CreativeMD 
Is it possible to also set the `EntityPlayer#bedLocation` when faking the player as sleeping? There might be more mods that expect a bedLocation to be present when the player is sleeping since this is always the case in Vanilla.


As a workaround we could add an additional check to Vampirism (which probably should have been there in the first place). However, I really would like to avoid that as my 1.12 workspace is dusted and Gradle gave me a hard time the last time I tried to revive it.

**Comment by CreativeMD** [comment] 2020-12-27 19:09
Sorry for not responding earlier, I just set it bedLocation to 0,0,0. Hope that fixes the issue.

**Comment by maxanier** [comment] 2020-12-29 11:39
Awesome, thank you!

@Taknax let me know if the issue should still persist with the new PlayerRevive version

**Closed as completed by maxanier** 2020-12-29 11:39 UTC
Labels: bug, 1.12
