### ISSUE TITLE
Crash when starting up game with Guide-API 

### ISSUE THREAD

**Issue by Neglevin** [TeamLapen/Vampirism#348] opened 2018-08-16 19:26 UTC
## Versions
- Minecraft: 1.12.2                  
- Forge: forge-1.12.2-14.23.4.2749-universal.jar                  
- Vampirism: Vampirism-1.12.2-1.4.5                                           
Guide-API: Guide-API-1.12-2.1.6-61.jar

## Issue Description 
Whenever I try to launch Minecraft with any version of Guide-API installed (I tested it), it crashes as it's initializing. It seems to start up just fine if I disable Guide-API. It seems to happen with all versions of Vampirism as well. This wasn't happening earlier, so I don't know what went wrong. Any help would be appreciated.

## Reproduce Steps

Try to start up Minecraft with Vampirism and Guide-API installed

## Additional Information
https://pastebin.com/Nx6w6AQg

**Comment by maxanier** [comment] 2018-08-16 20:07
Thanks for testing and reporting. However this is a duplicate of #346.
Either update Forge to *2751 or somehow reload the MC assets (reinstall MC, not sure how this works, maybe there is an easier way)

**Closed as completed by maxanier** 2018-08-16 20:07 UTC
Labels: duplicate
