### ISSUE TITLE
Cyclic inventory resets after joining faction

### ISSUE THREAD

**Issue by Dmd026** [TeamLapen/Vampirism#916] opened 2021-04-16 10:50 UTC
I'm playing on a modpack with cyclic and vampirism, and when i turned myself into a vampire hunter, my items inside my extended inventory got erased. I'm pretty sure this is a bug

**Comment by Cheaterpaul** [comment] 2021-04-16 18:01
Duplicate of #880

**Closed as completed by Cheaterpaul** 2021-04-16 18:01 UTC
Labels: bug, modcompat, 1.12, unconfirmed
