### ISSUE TITLE
[Bug] Game crashes upon transforming into a bat

### ISSUE THREAD

**Issue by Inonedn** [TeamLapen/Vampirism#673] opened 2020-04-21 14:34 UTC

**Comment by Cheaterpaul** [comment] 2020-04-21 15:01
pls provide some version info and other useful information such as the log files.

i cannot reproduce this with the newest 1.15 version

**Comment by ThePerfectLink** [comment] 2020-05-09 05:36
Yep, fairly common problem for the newest version for 1.15.2, simply turn into a bat while viewing yourself (3rd person) or view another player as a bat and immediately be ejected out of your world.

**Comment by maxanier** [comment] 2020-05-09 09:31
Without a crash report there is nothing we can do since we cannot reproduce it.

**Comment by ThePerfectLink** [comment] 2020-05-10 04:32
[crash-2020-05-08_19.59.01-client.txt](https://github.com/TeamLapen/Vampirism/files/4605147/crash-2020-05-08_19.59.01-client.txt)

**Comment by maxanier** [comment] 2020-05-10 09:33
Thank you.
Unfortunately, the game crashes at a position where the crash log does not give sufficient information alone.
I still cannot reproduce it with the exact versions of Vampirism and Forge, so I assume there is some kind of mod conflict.
Could you export your MultiMC instance and drop it here:
https://cloud.maxgb.de/s/gt5EbF9bfWAG9ie
(I only need the config and mods folder as well as the saves folder if you can reproduce it in SP)
Thank you

**Comment by maxanier** [comment] 2020-05-13 09:26
Bad bot!

If we can get a modpack, where this crash occurs we can try to narrow down the conflicting mod. Otherwise there isn't much we can do, unfortunately

**Comment by ThePerfectLink** [comment] 2020-05-13 20:45
ok here's the instance export from MultiMC
https://file.io/RW5jVq0U

**Comment by maxanier** [comment] 2020-05-13 23:37
Hey thank you very much. Unfortunately, the link appears to be dead :/

Am 13. Mai 2020 22:45:28 MESZ schrieb ThePerfectLink <notifications@github.com>:

**Comment by ThePerfectLink** [comment] 2020-05-14 00:10
Well, that's just the worst file hosting service ever, no matter. I put it on my dropbox now https://www.dropbox.com/s/6tij1k7xyx9z8px/%5B1.15.2%5D%20Modpack%20Omega.zip?dl=0

**Comment by maxanier** [comment] 2020-05-14 22:38
Thank You.
I have narrowed it down to upgrade aquatic.
The crash is caused by a bug/design issue in that mod. I will create a issue over there.
Unfortunately, there isn't much I can do on our end :/

**Comment by maxanier** [comment] 2020-05-16 21:12
Should be fixed with the latest version of Upgrade Aquatic. Let me know if not

**Closed as completed by maxanier** 2020-05-16 21:12 UTC
Labels: bug, external, 1.15
