### ISSUE TITLE
Vampire Hunter Skills stop working after you leave the server[Bug]

### ISSUE THREAD

**Issue by DracoPhoenix42** [TeamLapen/Vampirism#831] opened 2021-01-19 04:55 UTC
## Versions

- Minecraft: 1.16.4
- Forge: 1.16.4-35.1.37
- Vampirism: 1.16.4-1.7.2 

- ModPack: 
![image](https://user-images.githubusercontent.com/77656504/104989156-a9b0bf80-59ce-11eb-9eeb-c18d1789a613.png)

 
When I rejoined the server I was still a vampire hunter yet could not access any of the skills or open the skill tree.
## Issue Description

 I started the Vampire Hunter questline and did the garlic infuser. Then I left it for a bit to find the right trainer, although I had to leave and rejoin. When I came back I was still a vampire hunter although I could not open the skill menu or access any other hunter features.

**Comment by maxanier** [comment] 2021-01-19 10:01
Duplicate of #829 

Unfortunately, I have not been able to reproduce it so far.
Can you reproduce this in single player?
(Create a new world with cheats enabled and use `/vampirism level vampirism:hunter 4` to immediately become a hunter level 4)

**Comment by DracoPhoenix42** [comment] 2021-01-19 17:53
Yes, I was able to reproduce ridiculously consistently. 
[https://youtu.be/9ryGlnNqsCQ](url)
^Video evidence of the bug, along with steps to reproduce in the description

**Comment by maxanier** [comment] 2021-01-19 18:08
Thank you for the video, I have done the exact same things as you have shown in the videos with the same mods as shown in the screenshot. For some reason everything works fine on my end :/
Some some further questions:
- Did you modify any of the configuration files or are you running a pre-made mod pack?
- I assume you are using Windows, which launcher are you using?
- Can you share your `options.txt` and `optionsof.txt` here? Maybe some game options is required to reproduce the issue

**Comment by DracoPhoenix42** [comment] 2021-01-19 18:19
1. I am just running the mods together, very little changed.
2. Window Forge 1.16.4
3. 
[options.txt](https://github.com/TeamLapen/Vampirism/files/5837802/options.txt)
[optionsof.txt](https://github.com/TeamLapen/Vampirism/files/5837805/optionsof.txt)

**Comment by maxanier** [comment] 2021-01-19 22:56
I have tried it again on windows with the vanilla launcher with the same options files and the exact same mods and it still does not happen.
Can you reproduce it again (create world, become hunter, leave, rejoin (without quitting the game in between)) and then upload your .minecraft/logs/debug.log here.
Maybe there is something in there.

Sorry for all the troubles, but since I cannot reproduce it I have to rely on you to test things.

**Comment by DracoPhoenix42** [comment] 2021-01-20 03:01
Alright, [https://youtu.be/7feE2Kdw0Jc](url)
[debug.log](https://github.com/TeamLapen/Vampirism/files/5839884/debug.log)
I will see if disabling opti-fine  changes anything (seen in thread)
(edit) Disabling opti-fine allowed it to function without the issue

**Comment by maxanier** [comment] 2021-01-20 11:44
Thank you again!
Yes, Optifine likes to mess things up in unexpected and concealed ways.

I still don't know what causes the problem, but at least I have an idea now.
It seems that Optifine is somehow preventing the first internal update packet to be send. However, I still don't know at which point and how exactly.

If my hypothesis is correct I can try to implement a workaround for that, so users can continue using Optifine with Vampirism.
Can you therefore use the linked Vampirism version, reproduce it again, run `/vampirism-test forcePlayerSync` and then upload the debug.log again. No need for a video this time.
http://cloud.maxgb.de/s/DMnAt7TNjTSwdSt

Thank you very much

**Comment by A-Table** [comment] 2021-01-20 19:54
Hi, I know you didn't ask me, but I couldn't help but test the experimental version of Vampirism. I followed the instructions you provided, and it seems to fix the bug when using Optifine. Here's my debug.log and latest.log. Sorry if this was not useful.
[debug.log](https://github.com/TeamLapen/Vampirism/files/5844943/debug.log)
[latest.log](https://github.com/TeamLapen/Vampirism/files/5844945/latest.log)

**Comment by DracoPhoenix42** [comment] 2021-01-20 21:17
Alright, I tested the version, force player sync seems to have solved the issue.
[debug.log](https://github.com/TeamLapen/Vampirism/files/5845329/debug.log)
[latest.log](https://github.com/TeamLapen/Vampirism/files/5845331/latest.log)
Don't know if it will be useful but here you go. =)

**Comment by maxanier** [comment] 2021-01-20 21:46
Alright thank you both! (Didn't want to bother you both, so I did not ask you A-Table)
Based on the new log files I think I now what Optifine is messing up (even though I still don't know how and why).

I have implemented the initial sync in a different way now, hopefully this will fix this issue.
Can you try http://cloud.maxgb.de/s/cK6BXD5yNjLKLQZ
(Only) if that still does not work, I would need the debug.log again.

**Comment by DracoPhoenix42** [comment] 2021-01-21 03:24
As far as I can tell it has been fixed. =)

**Comment by maxanier** [comment] 2021-01-21 08:24
Awesome, thank you for testing.
The workaround will be integrated in the next official release, but you can just keep using the fixed version for now

**Comment by takashi1kun** [comment] 2021-01-22 20:15
I had this same bug, only that in Signle Player and when diying, your patch makes it so when i reenter the world, it is solved but if i die again the problem happens again.
video: https://streamable.com/oexoxc


EDIT: Okay since a instance  with +100 mods was a very dirty enviorment, i made a instance with only forge, optifine and vampirism, i was using the second test version you uploaded here and it happens as well, when i die, vampire level, skills, access to the skill tree and sucking blood disapears like in the video, after i did /vampirism-test forcePlayerSync it worked and all returned to normal, also returns to normal if i leave and load the save again. this is the log of the instance that was clean, i was not even using the tombstone mod, just vampirism+optifine+forge. All in single player

[debug.log](https://github.com/TeamLapen/Vampirism/files/5858461/debug.log)
[latest.log](https://github.com/TeamLapen/Vampirism/files/5858462/latest.log)

EDIT 2:
I uninstalled optifine and tested with only Vampirism and forge, the death bug persists

**Comment by maxanier** [comment] 2021-01-23 12:07
Thank you for reporting.
Didn't think about respawning, so my workaround fixed the world join but therefore made the respawn bug appear even without Optifine
Will be fixed in the next version

**Closed as completed** 2021-01-23 12:44 UTC
Labels: bug, duplicate, 1.16
