### ISSUE TITLE
Becoming a Vampire

### ISSUE THREAD

**Issue by unfamoushero** [TeamLapen/Vampirism#176] opened 2017-05-27 19:19 UTC
## Versions
- Minecraft: 1.10.2                   
- Forge: 8.0.99.99                      
- Vampirism: 1.1.0                                            

 The issue is that I can't see my blood bar (I see the standard hunger bar instead, which resets to half full any time i teleport or move between dimensions), I can't open the leveling menu to spend skill points, I don't get the big bright yellow border around my screen signifying being in sunlight, I can't see the number representing my vampire level that should be above my exp bar, and I can't see the red eyes on my own character. It should be noted however, other players in the multiplayer server I'm on see my name plate the appropriate purple vampire color, and see the red vampire eyes on my skin even though I don't. 

Additionally, I cannot use an altar of cleansing to make myself no longer a vampire, and using the vampire fangs again informs me that I am "already a vampire". For thoroughness sake I attempted to level up and was able to do so. I gained more hp and related passive effects, but levling up hasnt fixed any of the previous issues. I tried killing myself and that didn't change anything either, as well as restarting my minecraft several times.

It is worth mentioning that all other functionality for a level 1 vampire is working. I take weakness in sunlight, and at higher levels sunlight damages me and gives me nausea, can bite mobs, and have extra hp, as a vampire should, and can drink blood bottles (though I can't see my blood bar), and vampire hunter gear poisons me.

 As far as reproducting the steps of how this happened, prior to this I had contracted vampiris several times from being hit by npcs, but cured it using milk (not sure if this is relevent but thought I'd mention). Some time later I used the vampire fangs item to give myself vampiris since I was at that point finally ready to be a vampire. At which point I received the acheivement for becoming a vampire, but experienced the above issues. Potentially also worth mentioning is that this occured within 15 minutes prior to a server restart.

I don't have access to any of my player data currently since this is on a multiplayer server. However, from what my server admin tells me my player data for vampirism all looks fine.

**Comment by maxanier** [comment] 2017-05-27 23:40
Strange. It sounds like everything is working fine on server side, but your client does not know that you are a vampire.

Are you sure about that Forge version? Not sure if that even exist. And if that's actually the version that is displayed ingame, where did you get it from?

**Comment by unfamoushero** [comment] 2017-05-28 01:37
I got it as part of the mech and magic pack from the ATlauncher.

**Comment by unfamoushero** [comment] 2017-05-28 01:44
ForgeMultipart-1.10.2-2.0.0.31-universal
Forgelin-1.3.1
forge-1.10.2-12.18.3.2254-universal

are the files for forge I found in the folders for the pack. In game it says that the version was the one I listed in the original post, but it seems that wasn't accurate.

**Comment by unfamoushero** [comment] 2017-05-28 03:45
the vampire stuff works fine in single player, but on the server it doesn't. The admin reset my player data and I became a vampire again, this time by getting bit. After becoming a vampire the second time I still had the same issue.

**Comment by unfamoushero** [comment] 2017-05-28 03:48
Also I deleted the pack and reinstalled it and still have the same issue

**Comment by maxanier** [comment] 2017-05-28 13:50
Alright, then I need your .minecraft/log/fml-client-log (start the game, connect to the server, maybe drink some blood, then upload the log). Preferably to [Paste.ee](paste.ee) or similar.
Thx

**Comment by unfamoushero** [comment] 2017-05-28 15:25
Currently working on getting those logs to you in a zip file, though I thought I might also add that the server uses a hub world with portals that redirect to the server for the pack you actually want to use, though no one else seems to be reporting the same issues as I have been despite using the same hub world and modpack.

**Comment by unfamoushero** [comment] 2017-05-28 15:39
Alright let me know if any of these are the logs you were looking for, or if you need anything else from me. I couldn't open the fml-client-log, so I just attached a zip file with all the logs from my game, including "fml-client-latest.log".
[Vampirism Bug Report Logs.zip](https://github.com/TeamLapen/Vampirism/files/1034285/Vampirism.Bug.Report.Logs.zip)

**Comment by Yorkforce** [comment] 2017-05-28 18:43
Hiya, I'm the admin for the server in question, this is Unfamoushero's player.dat file incase it's any help for you.
https://www.mediafire.com/?8z5fe2n52c7c56p

We are running Forge version 2254 on a SpongeForge server but we are seeing no errors in the console or the logs.
If you need any further server specific info please let me know and I'll add whatever is required.

**Comment by maxanier** [comment] 2017-05-30 21:23
Thank you.
I took a look at the log files an the player file, but I still have no idea what is causing problem. The hub world makes the log kinda confusing.
Can you do the following?

1. Remove BlockDrops mod (temporarily as it causes a lot of spam in the log with the current Vampirism version)
2. Connect to to the Vampirism world/server.
3. Send a chat message containing "vampirism-test-connected" (so I can find it in the log file).
4. Run "/vampirism fang 1"
5. Send a chat message containing "vampirism-test-fang"
6. Try to use the altar of cleansing
7. Send a chat message containing "vampirism-test-cleansing"
8. Kill yourself
9. Send a chat message containing "vampirsim-test-respawn"

Then send me the fml-client-latest.log again pls.

Thank you very much :)

P.S. If you have any idea what might be different with your Minecraft instance compared to the other players.

**Comment by unfamoushero** [comment] 2017-05-31 01:35
While my minecraft boots up to perform that battery of tests I'll try to think through any potential differences...

I know that prior to joining the server I had extensively played in single player as a vampire hunter, whereas most people were new to the pack. Not sure how much that could/would effect it though, especially since deleting and reinstalling the info for the pack didn't change anything.

If I think of anything else I'll let you know.

**Comment by unfamoushero** [comment] 2017-05-31 01:44
Alright, did all the things you asked and here is the file
[fml-client-latest.zip](https://github.com/TeamLapen/Vampirism/files/1040081/fml-client-latest.zip)

**Comment by maxanier** [comment] 2017-05-31 08:13
Alright, thank you. I might have found the issue, but I did not find the reason it appears yet. Thinking about how to fix it now.

**Comment by unfamoushero** [comment] 2017-05-31 16:35
Sweet :D Let me know how that goes, if there is anything else I can do to help you figure this out, and if you find out anything.

**Comment by unfamoushero** [comment] 2017-06-01 00:45
Something I've noticed is I seem to have the exact same problem with cyberware on this server. I get the benefits, but am unable to bring up any menus related to my installed cyberware. (For Cyberware) I can't bring up any menus related to cyberware I've installed, and none of my HUD changes despite having installed a HUD lens, and the Robosurgeon keeps thinking I have no cyberware installed when I activate it. So maybe this is a problem with my minecraft or computer, rather than the mod(s)?

Update:
Some people have told me thats just a thing that happens with cyberware in multiplayer, and advised me to reconnect to the server. I'll try that and be back.

Update 2:
That didn't fix it, according to some Cyberware is just glitchy in general. Especially for multiplayer, but worth mentioning I guess anyway.

**Comment by maxanier** [comment] 2017-06-02 20:33
My current assumption is that this is caused by a entity id (the dynamically assigned ones, not visible to the enduser) messup between server and your client. (I've no idea how this can happen).

I have implemented a (partial) workaround for that problem. Pls try the new version if you can and tell me if anything changed. Also upload your fml-client-latest.log again, maybe even if the problem is completely solved.
https://minecraft.curseforge.com/projects/vampirism-become-a-vampire/files/2428466

Cyberware uses a similar system to sync their stuff between client and server, so it might be the same problem.

**Comment by maxanier** [comment] 2017-07-05 18:11
Did this fix the issue?

**Comment by maxanier** [comment] 2017-10-21 21:03
No answer -> Closing

**Closed as completed by maxanier** 2017-10-21 21:03 UTC
Labels: bug
