### ISSUE TITLE
[Bug] Hunter level reset after leaving world

### ISSUE THREAD

**Issue by HeyImPaul420** [TeamLapen/Vampirism#844] opened 2021-02-02 11:37 UTC
## Versions

- Minecraft: 1.16.4
- Forge: 35.1.4
- Vampirism: 1.7.3
- ModPack: N/A

## Issue Description
Basically i randomly lost (not sure when, i think when i relaunched the world) vampire hunter. I could not open the skills and i did not have the blue number above my levels.

## Reproduce Steps
Im not exactly sure, i think i just injected myself went back home and quit then the next day i got back into my world and vampire hunter was gone

**Comment by Cheaterpaul** [comment] 2021-02-02 11:52
This could be a duplicate of #831 if you have Optifine installed.

Can you upgrade to Vampirism 1.7.4 and try again?

**Closed as completed** 2021-02-28 12:33 UTC
Labels: bug, NeedsInfo, unconfirmed, 1.16
