### ISSUE TITLE
[Modcompat]: Minecraft Comes Alive Reborn

### ISSUE THREAD

**Issue by Arkaidium** [TeamLapen/Vampirism#1064] opened 2022-03-29 20:45 UTC
### Minecraft Version

1.18.x

### Forge Version

39.0.88

### Vampirism Version

1.8.0-beta

### Incompatible mod

modId = "mca" version = "7.1.0"

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Can't suck blood from MCA Reborn Villagers. The fangs don't appear in front of them like other mobs do.

### Reproduce steps

1. Load a world
2.  Become a vampire
3. Spawn, find, or cure a villager
4. Attempt to suck blood
<img width="960" alt="bug" src="https://user-images.githubusercontent.com/102626303/160703630-58081297-4246-43f8-ab57-e1e860e546fd.png">
As you can see, the fangs are not showing up to suck blood from this villager. I know this version of vampirism is still a beta, I just want to make sure this bug is patched in the next update for 1.18.1.

**Comment by Cheaterpaul** [comment] 2022-03-29 21:44
Duplicate of #1056


fixed by https://github.com/TeamLapen/Vampirism/commit/eee4fc77c690317adbb9ecf82d7c2cf00cf86560

will be fixed in the next version

**Closed as completed by Cheaterpaul** 2022-03-29 21:44 UTC
Labels: bug, modcompat, unconfirmed
