### ISSUE TITLE
[Bug]: Server Crash on Leveling Up to 8 Vampire

### ISSUE THREAD

**Issue by nekhs** [TeamLapen/Vampirism#1025] opened 2021-12-14 17:42 UTC
### Minecraft Version

1.16.x

### Forge Version

36.2.19

### Vampirism Version

1.8.4

### Modpack

private modpack

### Singleplayer/Multiplayer

Server

### What happened?

Server kicks everyone in the chunk out when I level up to 8 as a vampire. Not sure if it's a mod interaction or what - happens when using cheats to level up or when using the altar either one. (I did it with the altar first.) 

It is a bit of a kitchen sink pack and I don't actually know how to get a full mod list without typing every single mod out, forgive me.

There is no crash log on either the server or the client side as far as I can tell.

Only error it throws is a null pointer exception.

Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

Happened both in a vampire biome and in a vampire village.

My player data then isn't saved so I don't get to actually be level 8. 

For what it's worth, I've added and removed a couple of mods and changed the survive configuration to no longer do temperature things, so that might also be wonky, but I'm not really sure where to begin with this one.

### Reproduce steps

1. Load server, 
2. Level up to 8
3. Disconnect from server with null pointer exception

### Other relevant mods

Maybe Vampirism Integrations 1.6.1? I'm running Survive, Blood Magic, BOP, and Tinker's, which all seem to have compatibility through that.

**Comment by Cheaterpaul** [comment] 2021-12-14 19:32
can you upload the the crash-report, that is produced on crash or the debug.log file if there is no crash-report?

**Comment by nekhs** [comment] 2021-12-15 01:53
Hi! Sorry, I went to bed real quick after I posted that. The support agent I spoke with on my server hosting suggested I also send you my latest.log from the client, since it doesn't generate a crash report. So here's the debug log and the latest.log as well

[profile-results-2021-12-15_01.38.35.txt](https://github.com/TeamLapen/Vampirism/files/7715892/profile-results-2021-12-15_01.38.35.txt)
[latest.log](https://github.com/TeamLapen/Vampirism/files/7715893/latest.log)
.

Edit: What I did was, I started the debug, triggered the crash, and then stopped it. I hope that's enough!

Edit 2: It is reproducible in single player, let me get the log for you:
[crash-2021-12-14_20.02.45-server.txt](https://github.com/TeamLapen/Vampirism/files/7715935/crash-2021-12-14_20.02.45-server.txt)

Edit 3: OKAY SO I TRIED DISABLING MODS. Starting with the one I liked least. And it was Road Star, of all things, that was mentioned in the crash report and whose removal allowed me to continue playing after the level up. So I guess it was an incompatibility?

Edit 4: removed mod and relevant datapack from server and attempted level up; it kicked me out as usual.

Edit 5: turns out 'let me continue playing' was like, ten seconds more, and also it generated a crash log when I closed that instance so yeah.

Also tried removing Astral Sorcery in a single player instance and it still crashed, so that doesn't seem to be it.
[crash-2021-12-14_20.49.31-server.txt](https://github.com/TeamLapen/Vampirism/files/7716148/crash-2021-12-14_20.49.31-server.txt)

Edit 6: It also wasn't performant. At least I'm narrowing things down.

**Comment by nekhs** [comment] 2021-12-15 04:16
Update: After sifting through like half the mods that I use, I narrowed the crash down to two things: it happened in single player when opening the appearance menu, and I could no longer reproduce the crash in single player after removing Survive + UnionLib.  Will test further and report back.

**Comment by nekhs** [comment] 2021-12-15 04:29
Survive was indeed the culprit. Or at least UnionLib, upon which Survive depends. I don't know which it was, but ripping them out resolved the issue.

I have no idea why it would be that Survive of all things was causing this, but the issue cannot be reproduced without Survive present so ... -shrug.- 

It's also super heavy on the server so I'm gonna just leave Survive out, but if you're interested in resolving this incompatibility, that's what I've found.

**Comment by maxanier** [comment] 2021-12-15 21:03
Thank you for reporting.
So far I was not able to reproduce this issue. The crash-log is rather mysterious.

My only idea so far is, that this is somehow caused by VampirismIntegrations trying to do survive temperature compat, but the temperature system being disabled in Survive.

If you want to keep playing with Survive you could try to disable the `enableTemperatureVampires` config in `vampirism_integrations-common.toml`

**Comment by nekhs** [comment] 2021-12-16 17:32
Yeah the temperature system in survive is especially heavy and was causing tps issues so eh, while it's a nice mod, I'll just leave it out. 

What really confuses me is the first seven levels not causing the crash like .... ? But we still had the temperature system then, but ... man idk. 

Thanks for the awesome mods btw, I'm very much enjoying being a sad blood starved bat flapping around the nether in a panic because fire bad.

**Comment by maxanier** [comment] 2021-12-18 12:57
If you disabled the temperature system around the same time you reached level 8, then it was probably the temperature system.
I can't think of a reason why level 8 would be different from level 7.

Going to close this now, as it might be fixed in Integrations. If anyone else experiences this issue, please first disable `enableTemperatureVampires` in the `vampirism_integrations-common.toml` and only if the issue persists create a new ticket.

**Closed as completed by maxanier** 2021-12-18 12:57 UTC
Labels: bug, unconfirmed
