### ISSUE TITLE
Potion effects

### ISSUE THREAD

**Issue by Chinthor** [TeamLapen/Vampirism#87] opened 2016-07-02 00:32 UTC
It looks like vampires are immune to all potion effects. Good idea on the surface. But it can break some other mod mechanisms. For instance, Blood Magic 2 uses a potion effect to make mobs drop wills. Would be a shame if vampires don't interact with magic mods. Especially Blood Magic. I mean, c'mon.

As a suggestion, maybe give them a wide immunity against many things instead of full immunity to everything? Quite a bit more work, I know.

**Comment by maxanier** [comment] 2016-07-06 09:44
Strange, this is not intended. 
Unfortunately I cannot reproduce it that with just Vampirism, can you maybe upload your log file, after using a splash potion? 
Thanks

**Comment by maxanier** [comment] 2016-07-08 12:59
any further information?

**Comment by Chinthor** [comment] 2016-07-08 15:44
At least since the 1.10 update, they are affected by potion effects. Even
the soul snare effect from Blood Magic, though it takes more snares than
other mobs. In testing, however, they never drop demon wills. Even when
under the soul snare effect, even when killed by a sentient sword, they
drop none. Don't know if Vampirism needs to change how it identifies mobs,
or if Blood Magic needs to update how it registers mobs from other mods.

**Comment by maxanier** [comment] 2016-07-08 15:59
Ok then I'm going to close this issue, but I created a new one for the demon wills.
https://github.com/TeamLapen/Vampirism/issues/101

**Closed by maxanier** 2016-07-08 15:59 UTC
Labels: bug, modcompat
