### ISSUE TITLE
CTD on Creeper Explosion

### ISSUE THREAD

**Issue by Crescidious** [TeamLapen/Vampirism#530] opened 2019-10-02 12:19 UTC
## Versions
- Minecraft: 14.4                    
- Forge: 28.1.30                       
- Vampirism: Vampirism-1.14.4-1.6.0-alpha+20191001-1338                                            

## Go into a world and spawn a creeper with an egg and let it explode

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 02/10/19 13:16
Description: Ticking entity

java.lang.IllegalStateException: Cannot get ExtendedCreature from EntityCreature CreeperEntity['Creeper'/64, l='New World', x=87.50, y=4.00, z=-183.50]
	at de.teamlapen.vampirism.entity.ExtendedCreature.lambda$get$0(ExtendedCreature.java:47) ~[?:1.6.0-alpha+20191001-1338] {re:classloading}
	at de.teamlapen.vampirism.entity.ExtendedCreature$$Lambda$4153/1593858037.get(Unknown Source) ~[?:?] {}
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261) ~[?:?] {re:classloading}
	at de.teamlapen.vampirism.entity.ExtendedCreature.get(ExtendedCreature.java:47) ~[?:1.6.0-alpha+20191001-1338] {re:classloading}
	at de.teamlapen.vampirism.entity.ModEntityEventHandler.onLivingUpdate(ModEntityEventHandler.java:249) ~[?:1.6.0-alpha+20191001-1338] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_66_ModEntityEventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:312) ~[?:?] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1963) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.monster.MonsterEntity.func_70071_h_(SourceFile:51) ~[?:?] {re:classloading}
	at net.minecraft.entity.monster.CreeperEntity.func_70071_h_(CreeperEntity.java:142) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld$$Lambda$4126/42617017.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at de.teamlapen.vampirism.entity.ExtendedCreature.lambda$get$0(ExtendedCreature.java:47)
	at de.teamlapen.vampirism.entity.ExtendedCreature$$Lambda$4153/1593858037.get(Unknown Source)
	at net.minecraftforge.common.util.LazyOptional.orElseThrow(LazyOptional.java:261)
	at de.teamlapen.vampirism.entity.ExtendedCreature.get(ExtendedCreature.java:47)
	at de.teamlapen.vampirism.entity.ModEntityEventHandler.onLivingUpdate(ModEntityEventHandler.java:249)
	at net.minecraftforge.eventbus.ASMEventHandler_66_ModEntityEventHandler_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:312)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:1963)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at net.minecraft.entity.monster.MonsterEntity.func_70071_h_(SourceFile:51)
	at net.minecraft.entity.monster.CreeperEntity.func_70071_h_(CreeperEntity.java:142)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587)
	at net.minecraft.world.server.ServerWorld$$Lambda$4126/42617017.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:creeper (net.minecraft.entity.monster.CreeperEntity)
	Entity ID: 64
	Entity Name: Creeper
	Entity's Exact location: 87.50, 4.00, -183.50
	Entity's Block location: World: (87,4,-184), Chunk: (at 7,0,8 in 5,-12; contains blocks 80,0,-192 to 95,255,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Carinyc'/14, l='New World', x=87.98, y=4.00, z=-181.63]]
	Chunk stats: ServerChunkCache: 3683
	Level dimension: DimensionType{minecraft:overworld}
	Level name: New World
	Level seed: -8171200511215985367
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (80,4,-175), Chunk: (at 0,0,1 in 5,-11; contains blocks 80,0,-176 to 95,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 336 game time, 72192 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 24520 (now: false), thunder time: 33386 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4792176384 bytes (4570 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 4.0.0+61+ca3b447
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.30.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.30.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.30.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.30.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.30.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.30
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		jei-1.14.4-6.0.0.13.jar Just Enough Items {jei@6.0.0.13 DONE}
		Vampirism-1.14.4-1.6.0-alpha+20191001-1338.jar Vampirism {vampirism@1.6.0-alpha+20190930-2051 DONE, teamlapenlib@1.6.0-alpha+20190930-2051 DONE}
		forge-1.14.4-28.1.30-universal.jar Forge {forge@28.1.30 DONE}
		forge-1.14.4-28.1.30-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Carinyc'/14, l='New World', x=87.98, y=4.00, z=-181.63]]
	Data Packs: mod:jei, vanilla, mod:vampirism, mod:forge
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by maxanier** [comment] 2019-10-02 13:02
Looks like a duplicate of #526 
Pls update to 1.6.0-alpha+20191002-1213 and report if it should happen again.

**Closed as completed by maxanier** 2019-10-02 13:02 UTC
Labels: bug, unconfirmed
