### ISSUE TITLE
[Bug] Crash when loading new village - "Bound must be positive"

### ISSUE THREAD

**Issue by EnderMelody** [TeamLapen/Vampirism#654] opened 2020-04-02 11:48 UTC
Versions
- Minecraft:  1.12.2  
- Forge:  14.23.5.2847    
- Vampirism: Vampirism-1.12.2-1.6.2.jar                           

## Issue Description
when loading a new village, the server closed with a "bound must be positive" while ticking the totem from vampirism. Only happened once, then was able to enter the village fine. the village was not near any players at the time of the crash.

## Reproduce Steps
Not sure. Generating a village sometimes crashes the game.

## Additional Information
Crash report: https://paste.dimdev.org/ejaqixolow.mccrash
modpack on curseforge: https://www.curseforge.com/minecraft/modpacks/kermit-squad

**Comment by maxanier** [comment] 2020-04-04 17:45
It is not clear if it this is caused by Vampirism or another mod or merely triggered by it. It seems like another mod is messing with the villager professions/careers.
As this only happens rarely, only with this pack apparently, and 1.12 isn't really supported anymore. This won't be fixed, sorry.

**Closed as completed** 2020-05-15 10:29 UTC
Labels: bug, wontfix, unconfirmed
