### ISSUE TITLE
Turned Vampire Villager Trades[Bug]

### ISSUE THREAD

**Issue by princessbinas** [TeamLapen/Vampirism#428] opened 2019-05-20 14:20 UTC
## Versions
- Minecraft: 1.12.2                
- Forge: 14.23.5.2838                
- Vampirism: 1.5.0-beta.1                                 

## Issue Description

When trading with villagers to obtain blood bottles and hearts, the villagers do not give them despite showing the trades. 

## Reproduce Steps

- Obtain emeralds
- Find a villager (preferably a vanilla villagers such as a farmer)
- Have the villager turned into a vampire
- Scroll to a trade that has either "X emeralds for X blood bottles" or "X emeralds for X hearts." It does not matter as it happens with both trades.
- Attempt to trade for the blood bottles and/or hearts
- If the villager was a farmer, you will get bread most likely. Another vampire villager type (i.e. Blacksmith) might give you something different if you plugged in the right amount of emeralds. If the villager does not have a "X emeralds for X" trade, the villager will reject your offer.
- Exit out of the villager trade menu
- The trade disappears all together on the villager and never reappears no matter how many times you trade with the villager.

## Additional Information

I have tested this bug several times in different scenarios. This bug is present in both single player and on the official vampire server. No other mods seem to play a role in this bug and the forge version does not seem to matter. This bug is also consistent in how it happens. It always happens.

**Comment by Cheaterpaul** [comment] 2019-05-26 14:12
my research until now:
these bugs appear only in the official vampirism server modpack, even if you delete all mods except Vampirism
edit:
the forge version is the problem

**Comment by Cheaterpaul** [comment] 2019-05-26 15:25
i opened another issue for this problem (#434) and closing this, because first this is a issue of the modpack (vampirism has the issue with the forge version 14.23.5.2838/2836, while vampirism's forge 14.23.5.2768 works as intended.

I have already reported the problem on the server discord

**Comment by lunofe** [comment] 2019-05-26 15:51
Modpack has been updated, it should work now.

**Comment by maxanier** [comment] 2019-05-26 17:34
@Cheaterpaul But the issue still exists with the latest Forge version? So we need to find out what exactly is causing this and if it has to be fixed on Vampirism's side or Forge's side. Downgrading Forge is just a workaround.
Or did I misunderstand something?

**Comment by Cheaterpaul** [comment] 2019-05-26 17:42
you are right, i opened #434 , but we can continue here

**Comment by princessbinas** [comment] 2019-05-26 21:00
I know that the previous official release of Vampirism (1.4.9) did not have this issue, even with the forge version documented in my bug report and on wards. I am not sure how much this information will help.

EDIT: Also, here is the export for the modpack I use for my single player games. I designed it based off of a pre-existing modpack. This modpack includes logs and crash reports.
https://1drv.ms/u/s!AmEMGY-llTLSg_9vPFGl2-bhG07Ttw

**Comment by maxanier** [comment] 2019-05-27 10:56
Related to https://github.com/MinecraftForge/MinecraftForge/pull/5302
EntityVillager#getRecipes does not return the actual merchant buying list, but a copy now. Currently we are only modifying it once in EntityConvertedVillager#getRecipes, but since it is just a copy it does not persist.
Since buyingList is only protected and also saved to NBT, we probably could just add our trades just once after conversion directly to the actual list.

**Closed as completed** 2019-05-28 13:49 UTC
Labels: bug
