### ISSUE TITLE
Problems with a server

### ISSUE THREAD

**Issue by Kaiokengodx1000** [TeamLapen/Vampirism#1080] opened 2022-05-08 06:10 UTC
### Minecraft Version

1.16.x

### Forge Version

36.2.19

### Vampirism Version

1.8.8

### Incompatible mod

Morpheus 4.2.70

### Singleplayer/Multiplayer

Server

### What happened?

When Its just me and my friend in a server and I sleep in my coffin, instead of turning to night it just turns to day everytime

### Reproduce steps

1. Me and my friend join the server
2. I became a vampire
3. I made a coffin and it made it day instead of night
4. I retried to sleep in single player and it becomes night as it should

**Comment by Cheaterpaul** [comment] 2022-05-08 16:16
Duplicate of #776
and #964

This Problem is known by the Morpheus Team but they ignore it https://github.com/Quetzi/Morpheus/issues/84

**Closed as completed by Cheaterpaul** 2022-05-08 16:16 UTC
Labels: bug, modcompat, external, 1.16

**Comment by Cheaterpaul** [comment] 2022-05-08 16:48
Just use quark instead
