### ISSUE TITLE
[Bug] [1.12.2] Toughness bar disappeared

### ISSUE THREAD

**Issue by RedC4ke** [TeamLapen/Vampirism#680] opened 2020-05-05 10:16 UTC
## Versions
- Minecraft: 1.12.2                   
- Forge: 14.23.5.2847          
- Vampirism:  1.6.2                                           

## Issue Description

After becoming a vampire, my armor toughness bar disappeared. 

## Reproduce Steps
1. Have armor with toughness on it 
2. Become a vampire

## Additional Information
Also using VampirismIntegrations and VampiresNeedUmbrellas

**Comment by maxanier** [comment] 2020-05-15 10:23
I cannot reproduce it with just the three mods.
As this is not a critical bug, there is no obvious solution and 1.12 isn't really supported anymore, I am going to close this

**Closed as completed by maxanier** 2020-05-15 10:23 UTC
Labels: bug, unconfirmed
