### ISSUE TITLE
Bug with lvlup

### ISSUE THREAD

**Issue by Rias213** [TeamLapen/Vampirism#183] opened 2017-06-05 20:13 UTC
## Versions
- Minecraft: 1.11.2               
- Forge: 13.20.2310                     
- Vampirism: Vampirism-1.11.2-1.2.0-alpha+06-03-09-56                              

## Issue Description
I try to reach vampyrism lvl 5 and when i put book in the altar, game just crush.

## Reproduce Steps
Build altar, put hearts to it, try to put book

## Additional Information
mod list:
AbyssalCraft-1.11.2-1.9.4-pre-3
achunkloader-1.11.2-1.2.0
ActuallyAdditions-1.11.2-r109
AutoRegLib-1.1-4
Baubles-1.11-1.4.5
bdlib-1.13.2.7-mc1.11.2
BetterFoliage-MC1.11.2-2.1.5
BetterFps-1.4.4
BiblioCraftv2.3.0MC1.11.2
BiomesOPlenty-1.11.2-6.1.0.2238-universal
BloodMagic-1.11-2.1.10-79
Botania r1.9-343
buildcraft-7.99.4
compatlayer-1.11.2-0.2.9
Durability Show-1.11.2-4.1.0
ElecCore-1.11-1.7.418
embers-0.214
EnchantingTable-1.11-1.1
endertanks-1.11.0-1.5.5
FastLeafDecay-v12
forestry_1.11.2_5.3.3.96
GraveStone Mod 1.7.2
Guide-API-1.11.2-2.1.1-52
Hwyla-1.8.13-B26_1.11
iceandfire-1.1.0
InfernalMobs-1.11.2
InventoryTweaks-1.62+beta.89
IvToolkit-1.3.3
jei_1.11.2-4.3.6.282
journeymap-1.11.2-5.4.6
JustEnoughResources-1.11.2-0.6.4.6
llibrary-1.7.6-1.11.2
Mantle-1.11.2-1.2.0.26
mcjtylib-1.1x-2.3.11
MouseTweaks-2.8-mc1.11.2
muon_0.1
mysticalagriculture[1.11.2]-1.5.4
OptiFine_1.11.2_HD_U_B9
Pam's HarvestCraft 1.11.2h
Psi-r1.1-47
Quark-r1.2-92
RecurrentComplex-1.3.2
refinedstorage-1.4.10
rftools-1.1x-6.01
RoguelikeDungeons-1.11.2-1.6.6
roots-2-0.018
shetiphiancore-1.11.0-3.4.5
TConstruct-1.11.2-2.7.0.26
Tinkers' Addons-1.11.x-1.0.5
TinkerToolLeveling-1.11.2-1.0.1
Vampirism-1.11.2-1.2.0-alpha+06-03-09-56
zz-backpacks 1.11.2 - 3.1.6

**Comment by maxanier** [comment] 2017-06-08 20:31
Thx for reporting, I will investigate this tomorrow

**Comment by maxanier** [comment] 2017-06-09 09:27
Which book are you trying to insert?
There is a bug which crashes the game if trying to insert a wrong item, but I cannot reproduce this issue when inserting a "vampire book" ("Ancient writing")-

**Comment by maxanier** [comment] 2017-07-05 18:10
Does this issue still exist?

**Comment by maxanier** [comment] 2017-07-13 12:51
Closing because older than one month

**Closed as completed by maxanier** 2017-07-13 12:51 UTC
Labels: bug
